### ISSUE TITLE
EditMOM3 does not offer url attribute to cei:graphic

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#1004]
After adding a cei:graphic element to cei:figure in EditMOM3 user is not offered any attribute to add, although schema allows `@url`.

**Comment by GVogeler** [comment]
This is caused by CEI.XSD, which defines cei:graphics twice instead of pointing to the existing definition.

**Comment by StephanMa** [comment]
Fixed and deployed
