### ISSUE TITLE
cei.xsd and cei10.xsd are not in sync anymore

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#1006]
cei.xsd is the master schema, to which cei10.xsd a less restrictive version expressed in W3 XML schema 1.0, i.e. without some assertions. Both schemata should be in sync apart from the definitions possible with XSD 1.1 (`xs:assert` and related for the handling of `@value` and `cei:date`). Currently there are some minor differences (order of naming elements ...) which should not be case to make maintenance easier.

**Comment by GVogeler** [comment]
see also #205

**Comment by StephanMa** [comment]
I don't know if this is necessary... cei10.xsd is not used anywhere.
Will merge it nonetheless

**Comment by StephanMa** [comment]
closed by #1007

**Comment by GVogeler** [comment]
> I don't know if this is necessary... cei10.xsd is not used anywhere.
When deleting app/cei/xsd/cei10.xsd and the reference to it in app/cei/cei.app.xml (....) EditMOM3 fails to validate: `schema_reference.4: Failed to read schema document `xmldb:/db/XRX.live/mom/app/cei/xsd/cei10.xsd`, because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not .` I have to admit, that I have not clue, where the reference to cei10 is in the code.

**Comment by GVogeler** [comment]
If we really want to get rid of cei10.xsd we will probably have to dive into the exist-db-validation implemented in the exist-db version in use in MOM-CA (see https://github.com/icaruseu/mom-ca/issues/205#issuecomment-756764560 for some details, how I come to this idea, which might be wrong, @StephanMa)
