### ISSUE TITLE
Base map is not displayed anymore

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#1023]
e.g. the archives location map in https://www.monasterium.net/mom/fonds:
![grafik](https://user-images.githubusercontent.com/324006/106398981-5bf87600-6416-11eb-9e89-782970286cbf.png)
JavaScript console says that https://api.tiles.mapbox.com/v4/mapbox.streets/4/8/5.png returns a "410
Gone" error.

**Comment by GVogeler** [comment]
see https://stackoverflow.com/questions/64073635/blank-map-tiles-error-410-gone-mapbox-leaflet-js for a possible solution.

**Comment by StephanMa** [comment]
reworked API call
Changes deployed and waits for merging
