### ISSUE TITLE
`cei:sealCondition` is not displayed

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#1061]
https://www.monasterium.net/mom/DE-StaAWuerzburg/Heidingsfeld/25/charter has markup for `cei:sealCondition` which is currently not displayed at all in https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/charter/xsl/cei2html.xsl#L994-L1060 .

**Comment by GVogeler** [comment]
Proposal to solve this (and #1001, and #563 ): https://github.com/icaruseu/mom-ca/compare/master...NTsch:seals#diff-4a564f8bae64ac5bd66d1c1ba18f1d97b417fcfab0adec88b6ef2ad6a6aa0463

**Comment by NTsch** [comment]
Closed by #1062.
