### ISSUE TITLE
SKOS-editor should be accessed from the saved-vocabularies page

### ISSUE THREAD

**Issue by NTsch** [icaruseu/mom-ca#1072]
The SKOS-editor is currently accessed from the MyArchives page. Accessing it from the saved-vocabularies page would make it more obvious to the user that it is the personal copy that is being edited.

**Comment by GVogeler** [comment]
If I see this correctly, currently the user can only access the IllUrk-Vocabulary via the "SKOS-Editor" menu in https://www.monasterium.net/mom/my-archive. This is not expected behaviour.

**Comment by GVogeler** [comment]
Probably, replacing https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/skos-editor/widget/skos-editor.widget.xml#L30 with `<xrx:expression>doc(concat(metadata:base-collection-path('controlledVocabulary', 'private'),  '/', request:get-parameter("skos", ""), '.xml'))</xrx:expression>` could make the call dynamic and add a `?skos` parameter to the API.

**Comment by NTsch** [comment]
Closed by acaf665df033aa5bbaf8b5588388ea3a3d49e79b.
