### ISSUE TITLE
allow bibl-element in witness-element in CEI schema

### ISSUE THREAD

**Issue by NTsch** [icaruseu/mom-ca#1073]
In the Fontenay corpus, certain witnesses are written as follows:

`<witness n="a"><bibl sameAs="#Plancher1739"><biblScope>t. I, preuve p. xxxvii, n° L</biblScope><note>D’après C</note></bibl></witness>`
`<witness n="b"><bibl sameAs="#Laurent1907"><note>b. Fragment réimprimé d’après a : </note></bibl></witness>`

These are prints of charters, which can be treated as either editions (encoded as`cei:listbiblEdition/cei:bibl`), textual witnesses (preferably encoded as `cei:witness/cei:bibl`), or both. Allowing `cei:bibl` in `cei:witness` would make it easier to represent a print as a textual witness.

**Comment by GVogeler** [comment]
see https://github.com/GVogeler/CEI2TEI/issues/51 for the initial use case.

**Comment by GVogeler** [comment]
So we assume that `cei:witness[not(cei:archIdentifier)]/cei:bibl` represents a printed textual witness. As the change is easy, let's go for it!
