### ISSUE TITLE
How-to-cite uses non-capitalised Monasterium.net name

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#1090]
The How-to-cite-section in cei2thml.xsl should use the conventional naming of Monasterium.net with a capitalized 'M' at the beginning.

**Comment by NTsch** [comment]
This seems to come out of [charter.widget](https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/charter/widget/charter.widget.xml#L1278), [my-charter.widget](https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/charter/widget/my-charter.widget.xml#L514), and [saved-charter.widget](https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/charter/widget/saved-charter.widget.xml#L332). I've also found the non-capitalized spelling in [notes2pdf](https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/bookmark/xsl/notes2pdf.xsl#L43) and [cei2pdf](https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/charter/xsl/cei2pdf.xsl#L47) - I'll include all of these in the fix.

**Comment by GVogeler** [comment]
solved with PR #1091
