### ISSUE TITLE
Hinweis auf die "letzte importierte Datei" in der Importseite nur  für Rolle Metadata Manager

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#14]

**Comment by strec** [comment]
Die Importseite wird dem Nutzer ja nur angezeigt, wenn er die Rolle Metadata Manager hat, sonst kommt die Meldung 
https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/charters/widget/import-charters.widget.xml#L344

Oder aber der Nutzer ist nicht Metadata Manager, dafür aber der "Community" des Archivs zugehörig:
https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/charters/widget/import-charters.widget.xml#L302

Ist das so gemeint, dass Nutzer, die der "Community" des Archivs zugehören und keine Metadata-Manager sind, den Hinweis auf die letzte importierte Datei nicht erhalten sollen?

Also bei den Subwidgets hier 
https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/charters/widget/import-charters.widget.xml#L287
jeweils durchgehen und bei jedem (z.B. beim Excel hier
https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/charters/widget/import-info-excel.widget.xml#L64)
noch nen "xrx:auth" drum herum legen, in dem erneut auf Rolle Metadata-Manager geprüft wird...?

Ist das das erwünschte Verhalten der Anwendung? Die eigene Archiv-Community ist ja hier schon ziemlich eng gesteckt. Vielleicht möchte man ja wissen, was in der eigenen Community als letztes passiert ist...?

**Comment by GVogeler** [comment]
Das Speichern der letzten importierten Datei war m.W. nur eine Hilfe für schief gelaufene Importvorgänge, also nur für Experten sinnvoll. "Community" sind Archivare, die damit nicht konfrontiert werden müßten. @Daniel, kannst Du mit dem Bernhard bald mal besprechen, wie Du Dir einen übersichtlichen Import-Workflow für einen Archivar vorstellst?

**Comment by yngwi** [comment]
@GVogeler Was ist denn die *Archive-Community*?

----

@strec Die Import-Seite sollte meiner Ansicht nach nur für `Metadata-Manager` angezeigt werden, genauso wie der rote Balken mit den Bestandsaktionen. Ich dachte allerdings bisher, dass dem so und anders so wäre. Ich habe zumindest noch nie gesehen, dass eine der Funktionen, die zur Verwaltung von Beständen im Allgemeinen vorgesehen ist, von irgendjemand anderem als Karl und mir als Bestandsmanager benutzt wurde.

---

Der Importvorgang im Allgemeinen ist meiner Meinung  nach schon in Ordnung so wie er jetzt ist. 

Eventuell ließen sich die einzelnen Schritte noch mit Kurzinformationen versehen, damit einem nicht ganz so fixen Archivar, der die Funktionalität nutzen möchte/soll klar ist, was eigentlich jeweils passiert. Zusätzlich wäre praktisch wenn automatisch nur nicht-leere Zeilen in Excel-Files ausgewählt würden (siehe #41). 

Am wichtigsten wäre aber wohl ein "Übersetzen" von potenziellen Fehlermeldungen (v.a. im Bezug auf `cei:date` bzw. `cei:dateRange`, da sind am häufigsten Fehler drinnen, die den Leuten nicht klar sind).

**Comment by GVogeler** [comment]
https://github.com/icaruseu/mom-ca/wiki/authentication#community

@Strec can you expand this section (in particular how a user is 
attributed membership of a community)

Am 14.04.2015 um 11:48 schrieb yngwi:

**Comment by strec** [comment]
The user-administrators are responsible for adding people to a community. Currently they are the ONLY ones, who can do that.

To add users to a community, the community:add function has to be called. This is only ever done internally inside the community:refresh function. This function is only ever called once inside the mom/app/archive/service/manage-archivists.service.xml

This service in turn, can currently only be accessed by user-administrators through the widget
mom/app/archive/widget/manage-archivists.widget.xml

In the widget, a singular archive context is established through the archiveid (which is extracted from the url). The user-administrator can add new so-called "archivists" to the current contextual archive. The user-administrator is presented with a list of all users and also with a list of the archivists in place in the context of this archive already. (This is similar to the interface when choosing metadata-managers as a user-administrator for example). When clicking on the "Save"-button, all previous minus the removed archivists and plus the newly chosen archivists are submitted to the manage-archivists.service.xml. Also the current contextual archive-id expanded and transformed to an atom-id is submitted.

The service on the other hand does nothing else than taking the submitted archivists and archive-atomid and calling the function
community:refresh($archivists, $archive-atomid)

That is all it does. $archivists contains a sequence of emails by the way. These are used to identify the users.

Inside the community:refresh function, all users, that are part of the current archive-id community are removed from the community (with community:remove). Then all the archivists, that were submitted by the user-administrator through the service just a moment ago are added to the community as members (with community:add).

The actual community membership is modelled in the following way: Each user has a file inside his user collection, in which the communities he/she is belonging to are listed. They are inside the <communities> element. Like so:
```<xrx:communities xmlns:xrx="http://www.monasterium.net/NS/xrx">
    <xrx:community>tag:www.monasterium.net,2011:/archive/DE-HStAMa</xrx:community>
    <xrx:community/>
</xrx:communities>```

Currently there are only about eight users, which belong to a community, and another six (if I counted right), who once belonged to a community, but no longer do. This can be deduced from communities elements, which do not contain a community like so:

```<xrx:communities xmlns:xrx="http://www.monasterium.net/NS/xrx">
    <xrx:community/>
</xrx:communities>```

By the way, the underlying functionality starting with community:refresh is all happening inside the "auth" app.
It only consists of a few XQuery-modules, which themselves depend on other again...
https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/core/app/auth/auth.app.xml#L32

For the community-things the most important (contextually more or less) top-level XQuery-modules are of course community.xqm and member.xqm

The actual access to managing the respective community-members is done through the "archive" app as mentioned above and only accessible by user-administrators.

**Comment by strec** [comment]
https://github.com/icaruseu/mom-ca/wiki/authentication#community expanded!
