### ISSUE TITLE
mechanism for links to external charter images broken

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#163]
http://monasterium.net/mom/DE-HStASt/HStASt_A502/Stiftsarchiv_St_Paul_im_Lavanttal_St_Blasien_U_311/charter, 
http://monasterium.net/mom/IT-ASFi/DNBorgoSanSepolcro/00011618/charter, http://monasterium.net/mom/DE-HStASt/HStASt_A502/A_502_U_1/charter sollten
1. ein Thumbnail der Urkunde anzeigen
2. als Link auf die Urkunde auf der Seite des Landesarchivs Baden-Württemberg enthalten (`http://www.landesarchiv-bw.de/plink/?f=1-1336081`)

**Comment by StephanMa** [comment]
Im Beispiel http://monasterium.net/mom/DE-HStASt/HStASt_A502/A_502_U_1/charter ist das Problem, dass dort zwei Images hinterlegt worden sind. Der erste Link allerdings, ist lediglich der Verweis auf den Eintrag im Findbuch in Stuttgart. Deshalb kann dort kein Thumbnail angezeigt werden. Der zweite Link verweist auf das Thumbnail.

**Comment by GVogeler** [comment]
Das LABW und das ASFI sind Archive, die keine Bilder in MOM veröffentlichen, sondern nur einen Platzhalter (Thumbnail im Stuttgarter Fall, ein allgemeines Bild im Fall von Florenz), der als Link auf die Archivpräsentation der Urkunde fungiert. Es gibt also die Information über den originalen Speicherort gibt (`cei:witnessOrig/cei:archIdentifier/cei:ref/@target`) und über das anzeigte Bild (`cei:witnessOrig/cei:figure/cei:graphic`). Derzeit gibt es noch keinen Mechanismus, der in den Daten erkennt, ob das Bild ein Platzhalter ist und deshalb auf archIdentifier/ref verweisen soll oder auf die Bild-URL. Mein Vorschlag wäre, das in cei:figure/@n='thumbnail' auszudrücken und bei der Anzeige zu überprüfen. Andere Vorschläge?

**Comment by GVogeler** [comment]
see the image template at https://github.com/GVogeler/mom-ca/blob/master/my/XRX/src/mom/app/charter/xsl/cei2html.xsl#L517 for a starting point in charter display and https://github.com/GVogeler/mom-ca/blob/master/my/XRX/src/mom/app/charter/xsl/cei2html.xsl#L1108 for the thumbnails in the "witness" section of charter display.

**Comment by StephanMa** [comment]
Maybe not directly into the charter-data.
But the reference to the archival destination is set when the fond is set to restricted.
The picture/thumbnail is shown anyway in the preview of the witness-section.

**Comment by GVogeler** [comment]
In the example above (Stuttgart) we have:
```
<cei:figure><cei:graphic url="http://www.landesarchiv-bw.de/plink/?f=1-1285176-1&ext=1"/></cei:figure><cei:figure><cei:graphic url="http://www.landesarchiv-bw.de/plink/?f=1-1285176-1"/></cei:figure>
```
the second `cei:figure` points only to the landing page (would be something like [`edm:shownAt`](http://pro.europeana.eu/files/Europeana_Professional/Share_your_data/Technical_requirements/EDM_Documentation//EDM_Definition_v5.2.7_042016.pdf#33), while the first contains a thumbnail. Currently we only have the general definition for the whole fond which handles the link in the head bar of the image (changing it to "To view the charter images, please visit the archive's homepage. >>" using `cei:witnessOrig/cei:archIdentifier/cei:ref/@target`.
If we stick to this solution, then we have to clean the data in the fonds of `DE-HStASt`. @yngwi what do you think which solution archives would prefer?
a) thumbnail/placeholder (as link) in the image section of the single charter view (change in application necessary)
or
b) only the link in the head line and a thumbnail of the image in the "text witness" section of the single charter view (change in data necessary, which is necessary anyway I would say as the shownAt-like pointer in the Stuttgart data is no image at all)
?
I would currently prefer solution b)
