### ISSUE TITLE
Excel import: comment-elements are erronously converted to bibl

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#17]
should be cei:diplomaticAnalysis/cei:p

**Comment by strec** [comment]
There can be multiple diplomatic comments. The cei stylesheets have an unbounded amount of diplomaticAnalysis/cei:p specified.
In the Excel-file there could be multiple columns with the heading "diplomatischer_Kommentar", each being put into its own <cei:p></cei:p> now.

**Comment by GVogeler** [comment]
As the Excel-import can offer only reduced functionalities compared to full XML it is enough to have one column "diplomatischer_Kommentar" which is converted into one single `cei:p`.

**Comment by strec** [comment]
It is cei:diplomaticAnalysis/cei:p as of commit abb1e8a in my fork strec /mom-ca
The possibility of having more than one column in the Excel-Sheet named "diplomatischer_Kommentar" is still present, but only having one works fine.

**Comment by strec** [comment]
This issue is no longer open.
