### ISSUE TITLE
display cei:index in Index-section of single charter view

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#171]
egal wo das Element vorkommt: z.B. http://www.monasterium.net/mom/IT-ASFi/DNStrozzianeUguccioni/00007661/charter

**Comment by StephanMa** [comment]
Should it be displayed as an "item" inside the Index-Section or seperate as "index"-item?

**Comment by GVogeler** [comment]
/"item" inside the Index-Section/: In the index section there should be three lists of indices: places (Orte) =`//cei:placeName`, persons (Personen) = `//cei:persName`, terms (Sachen) =`//cei:index` each with subgroups for the `@type`, giving the `@reg|@lemma|@sublemma` information an the element content.

**Comment by StephanMa** [comment]
The example does't contain any "type"-attribute inside the index-Tag. In this case, should it be displayed, too?

**Comment by GVogeler** [comment]
Yes

Am 31.03.2015 um 16:07 schrieb StephanMa:

**Comment by GVogeler** [comment]
`@type` cfr. #167
