### ISSUE TITLE
search2: "Browse in search results" should link to current charter

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#176]
links currently only to the position of the charter in the current block: e.g. http://www.monasterium.net/mom/search2?null=&sort=date&q=Notariatsinstrument&img=&context=&categories=&annotations=&option=and&block=15
=> count position of current charter in complete result list and put this into .../mom/[POSITION]/search-result?...

**Comment by JBigalke** [comment]
I'm on it.

**Comment by GVogeler** [comment]
follow ups:
layout of search result: cfr. #277
breadcrump linking: cfr. #278
