### ISSUE TITLE
 move all charter markup into cei namespace

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#192]
e.g. [SI_PAM](http://monasterium.net/mom/SI-PAM/Listine/fond)
at least VdUEdit needs cei:-prefixes to work
See #216 for problems with namespace handling in EditMOM3

**Comment by GVogeler** [comment]
Check if it is solved when moving to EditMOM3 cfr. #43

**Comment by GVogeler** [comment]
EditMOM3 cannot render the XML as well: http://monasterium.net/mom/SI-PAM/Listine/SI_PAM%7C0001_00001/edit?mode=full

**Comment by GVogeler** [comment]
I currently cannot find a method to identify the documents:
`//cei:text[@xmlns='http://www.monasterium.net/NS/cei']` returns  also entries with prefix.

**Comment by GVogeler** [comment]
Workaround:
1. Identify fonds with this problem (currently only SI-PAM/listine is known)
2. do an XSLT transformation with an XQuery update:

```
let $xslt := <xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:atom="http://www.w3.org/2005/Atom"
    xmlns:cei="http://www.monasterium.net/NS/cei"
    exclude-result-prefixes="xs"
    version="2.0">
    <xsl:template match="/">
        <xsl:apply-templates/>
    </xsl:template>
    <xsl:template match="*[starts-with(name(),'cei')]" priority="-1" mode="cei">
        <xsl:copy>
            <xsl:apply-templates select="@*[.!='http://www.monasterium.net/NS/cei']"/>
            <xsl:apply-templates select="*|text()" mode="cei"/>
        </xsl:copy>
    </xsl:template>
    <xsl:template match="*" priority="-2" mode="cei">
        <xsl:element name="cei:{{name()}}">
            <xsl:apply-templates select="@*[.!='http://www.monasterium.net/NS/cei']"/>
            <xsl:apply-templates select="*|text()" mode="cei"/>
        </xsl:element>
    </xsl:template>
    <xsl:template match="atom:content">
        <xsl:copy>
            <xsl:apply-templates select="@*"/>
            <xsl:apply-templates select="*" mode="cei"/>
        </xsl:copy>
    </xsl:template>
    <xsl:template match="*" priority="-2">
        <xsl:copy>
            <xsl:apply-templates select="@*|*|text()"/>
        </xsl:copy>
    </xsl:template>
    <xsl:template match="@xmlns[.='http://www.monasterium.net/NS/cei']"/>
    <xsl:template match="@*|text()" priority="-2">
        <xsl:copy/>
    </xsl:template>
</xsl:stylesheet>

for $u in collection('/db/mom-data/metadata.charter.public/SI-PAM/Listine/')//atom:content
let $u-ns := transform:transform($u,$xslt, ())
return update replace $u with $u-ns 
````

**Comment by StephanMa** [comment]
I was able to identify 3 charters which have some tags without any cei:namespace in it

 

/db/mom-data/metadata.charter.public/DE-UBHD/UrkLehmann/Urk_Lehmann_235.cei.xml

 

/db/mom-data/metadata.charter.public/SK-SNA/4201-RodRakovskyZRakovaALiptovskejStiavnice/44.cei.xml

 

/db/mom-data/metadata.charter.public/DE-StaAWo/Abt1AII/II-010.cei.xml

 

Identified by using the following Query

xquery version "3.0";

declare namespace atom = "http://www.w3.org/2005/Atom";

let $collection := collection("/db/mom-data/metadata.charter.public/")

let $charters := $collection//atom:content

let $missing := for $charter in $charters 

                let $test := $charter//*

                let $check := for $node in $test

                    let $hit := if(namespace-uri($node) = "") then $node else ()

                    return $hit

                return $check

let $return := for $entry in $missing

                let $uri := base-uri($entry)

                return $uri

return $return

Beware: generates a high server load! Was tested on a virtual maschine!

 

Von: GVogeler [mailto:notifications@github.com] 
Gesendet: Montag, 21. November 2016 09:23
An: icaruseu/mom-ca <mom-ca@noreply.github.com>
Betreff: Re: [icaruseu/mom-ca] move all charter markup into cei namespace (#192)

 

I currently cannot find a method to identify the documents:
//cei:text[@xmlns='http://www.monasterium.net/NS/cei'] returns also entries with prefix.

**Comment by GVogeler** [comment]
solved for SI_PAM with the XQuery above.
