### ISSUE TITLE
If >1 image in my-charter, then no image is displayed under the heading Text witnesses

### ISSUE THREAD

**Issue by maburg** [icaruseu/mom-ca#203]
![imgtextwitness](https://cloud.githubusercontent.com/assets/8348838/5916602/32e9bcc8-a613-11e4-9e1b-6c5a5669a049.jpg)
![no_imgtextwitness](https://cloud.githubusercontent.com/assets/8348838/5916649/9dc49e78-a613-11e4-89e4-52c3a4d381ab.jpg)

**Comment by GVogeler** [comment]
cannot confirm this behaviour anymore
