### ISSUE TITLE
Browsers from Spain get an XRX-Error

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#21]
<exception>
<path>/db/XRX.live/mom/app/xrx/main.xql</path>
<message>
exerr:ERROR Error while evaluating expression: <html xmlns="http://www.w3.org/1999/xhtml" id="tag:www.monasterium.net,2011:/mom/mainwidget/home">{let $x___ := "" let $whome:htdoc-entry := htdoc:get('tag:www.monasterium.net,2011:/mom/htdoc/home') let $whome:htdoc-title := htdoc:title($whome:htdoc-entry)/text() let $whome:htdoc-atomid := $whome:htdoc-entry/atom:id/text() let $whome:statistics := mom:statistics() return ( <head> <title>{ if($xrx:mainwidget/xrx:title/xrx:i18n) then i18n:translate($xrx:mainwidget/xrx:title/xrx:i18n) else() }{ if($xrx:htdoc//xrx:i18n) then i18n:translate($xrx:htdoc//xrx:i18n) else() }&#160;{ string-join(subsequence($xrx:tokenized-uri, 1, count($xrx:tokenized-uri) - 1), '|') }&#160;-&#160;{ conf:param("platform-browser-title") }</title> <link rel="stylesheet" type="text/css" href="/mom/css/?atomid=tag:www.monasterium.net,2011:/mom/widget/home"/> </head>, <body data-xrx-widget="tag:www.monasterium.net,2011:/mom/portal/default">{ if(auth:matches(<xrx:rule xmlns:xrx="http://www.monasterium.net/NS/xrx"> <xrx:user/> <xrx:role>translator</xrx:role> </xrx:rule>)) then <div class="xrx-translate-page-link"> <a href="/mom/translate?id=tag:www.monasterium.net,2011:/mom/widget/home">‣&#160;{ i18n:translate(<xrx:i18n xmlns:xrx="http://www.monasterium.net/NS/xrx"> <xrx:key>translate-page</xrx:key> [...]

**Comment by StephanMa** [comment]
Found two Errors which produce this error:

The first Error is inside the 
/my/XRX/src/mom/app/i18n/i18n.app.xml. There were two Languages defined with the same "old" Key. "es" for espanol and eesti. Changed eesti to "et".

The second Error should have occured many times. Somehow it just effects this language Setting stuff. Changed /my/XRX/src/core/app/conf.xqm concerning setting the variable $conf:project-name and $conf:xrx-live-collection-name. Sometimes it occurs that there are more then 1 Projectname inside the System. Now just the first entry is used by the System. Before i commit the changes, i would like to test it with some more Data. But this Patch workes on my current System with a Browser with "Accept-Language" = "es"
