### ISSUE TITLE
EditMOM3 is tricky with namespace definitions in the root element

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#216]
charters with `<atom:entry xmlns:atom="http://www.w3.org/2005/Atom" xmlns:cei="http://www.monasterium.net/NS/cei">`cannot be saved, only if you delete the xmlns:cei-declaration `<atom:entry xmlns:atom="http://www.w3.org/2005/Atom">` they are saved.

**Comment by JBigalke** [comment]
If you change the xml in EdtiMOM3 the Editor changes:
 `<atom:entry xmlns:atom="http://www.w3.org/2005/Atom" xmlns:cei="http://www.monasterium.net/NS/cei"><atom:id>` to `<atom:entry xmlns:cei="http://www.monasterium.net/NS/cei"><atom:id xmlns:atom="http://www.w3.org/2005/Atom">`. In the my-collection-save.service.xml there is an Error in line: 35  `<xrx:expression>$data//atom:id/text()</xrx:expression>`.
 I try to find where EditMOM3 changes the xml and why.

**Comment by GVogeler** [comment]
@JBigalke schreibt: Ich habe das mal in der Datenbank überprüft und keine .xml gefunden 
indem das vorkommt.
Ich selbst habe den Fehler auch nur reproduzieren können indem ich in exide einfach direkt die gespeicherte .xml verändert habe.
