### ISSUE TITLE
EditMOM3 "all saved" response occurs even when the document isn't stored in the database

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#217]
When modifying a document without appropriate rights in the database or with unsupported xml like https://github.com/icaruseu/mom-ca/issues/216 EditMOM3 gives the "All changes saved" even if the data isn't stored correctly.

**Comment by GVogeler** [comment]
Pascale Sutter (Zürich) reports that several documents aren't stored in the database in this way on two different days and machines in a non reprocucable manner.

**Comment by GVogeler** [comment]
@gioele sagt: Das sind zwei Probleme:

1) der Server soll nicht "OK" antworten, wenn es Fehler gibt;
2) der Client soll nicht dem Server vertrauen.

Für das Problem 2 soll der Client:

* die aktuelle Datei schicken,
* die Datei zurückholen und das in einem Zwischenspeicher speichern,
* die aktuelle Datei mit die zurückgeholt Datei vergleichen.

Wenn sich Unterschiede ergeben, muss der Client mindestens eine Warnung 
vorzeigen.

**Comment by JBigalke** [comment]
Zumindest bei dem Problem von: "Issue #216 EditMOM3 is tricky with namespace definitions in the root element" Gibt es ein Problem das verhindert das er die my-collection-save.service.xml aufrufen kann. In dieser wird im grunde nix anderes gemacht wird als die charter in die Datenbank zu speichern. Ich habe jetzt in die function die die my-collection-save.service.xml aufrufen soll geschrieben das wenn es funktioniert hat soll die message: "All changes saved." erscheinen und wenn nicht "Failed to save changes."

**Comment by GVogeler** [comment]
#221 könnte ein Workaround sein, den Benutzern die Sicherheit zu geben, ihre Änderungen auch bei abgebrochener Verbindung zum Server / gescheiterter Speicherung zu sichern.

**Comment by GVogeler** [comment]
@JBigalke  schreibt: Test über Checksum hat als Problem ist, dass jedes mal wenn die Charter gespeichert wird automatisch ein update-timestamp gemacht wird. Das sorgt dafür das die Daten sich immer unterscheiden und damit die überprüfung durch Checksums nicht funktionieren kann.

Um zu testen um die Änderungen durch den MomEditor richtig gespeichert 
wurden könnte es also in meinen Augen reichen wenn wir nur den content 
selbst testen, also ab dem Tag <atom:content>

**Comment by GVogeler** [comment]
closed with #307
