### ISSUE TITLE
Download a complete (private) collection as XML

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#218]
would give the users the feeling of more control ("I want to backup/reuse my data")

**Comment by GVogeler** [comment]
and would allow them to reuse their data in other environements.

**Comment by StephanMa** [comment]
How should this download look like?

should it be one big file or several?

**Comment by GVogeler** [comment]
Prefered solution would be one big file, but a zip file with all single files would be ok as well. But issue task has no priorities!
