### ISSUE TITLE
EditMOM3 expects as URI-reference a special UUID although atom:id is unique

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#226]

**Comment by StephanMa** [comment]
Switching to atom:id is a problem. If two users are editing the same charter inside there own collections, there is no uniqueness.
Maybe the user-id has to be added to the atom-id. This would make it more unique.

**Comment by GVogeler** [comment]
we need a locking mechanism for this:  #152

**Comment by StephanMa** [comment]
The UUID for the Editor is based on the Atom:id.

Inside the Service /mom/service/my-collection-items, the Atom:id of the Charter will be truncated to the last Token of the Atom:id. So, to my Mind, there are no Changes necessary.

**Comment by GVogeler** [comment]
As far as I have understood EditMOM3 relies on the fact, that this last token is unique in `mom-data/metadata.charter.public`. This will certainly cause problems when editing existing documents in which this last token is only unique in the current collection/fonds. As the `atom:id` is by definition unique I would suggest to replace the uuid with the atom:id and use the uuid-mechanism only for freshly created charters (even there I see a general need for user defined IDs as a system of canoncical reference, but that's nothing we have to solve now).

**Comment by StephanMa** [comment]
Is done with Issue #43 

Call for Editing a Charter is now build the same way as displaying the Charter, e.g.
http://localhost:8181/mom/DE-LANW/Testimport_CEI/281/edit will call the Editor. The ATOM-ID is now extracted by the given URI

**Comment by StephanMa** [comment]
Should be fixed with #340
