### ISSUE TITLE
Prepare EditMOM3 for MOMAthon

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#227]
secure saving: #217 , #220 , 
atom:id instead of last token/UUID: #226 
adapt EditMOM3-template to existing charters: #296

and in general: #43

**Comment by StephanMa** [comment]
The Editor has to be dynamically to allow some restricted and limited Controls for different issues, e.g.
Just let the User edit cei:date or cei:placeName

**Comment by GVogeler** [comment]
closed with #330
