### ISSUE TITLE
move to Java 8

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#23]
Java 7 didn't work because of an SQL extension added to the standard eXist installation
With Java 8 we have no experience.

**Comment by StephanMa** [comment]
Tested it on local Installation.
Could install mom with eXist 2.2 with Java 7.
Now i give Java 8 a try.

**Comment by GVogeler** [comment]
see #24

**Comment by GVogeler** [comment]
debian8 unterstützt java6 nicht mehr
