### ISSUE TITLE
switch to new version of eXist

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#24]
moved to #589

**Comment by StephanMa** [comment]
Local installation mom with eXist 2.2 and Java 7 was successfull. 
Now i am trying it with Java 8.
Currently i just changed build.xml from the mainproject.

**Comment by GVogeler** [comment]
@gioele has encountered strange behaviour in eXist 2.2 (result number of request wasn't as expected by data) - we should try to build a test scenario to validate the new version before deploying it.

**Comment by StephanMa** [comment]
Changed Sourcefiles can be shared if someone want to use the new eXist-Installation.
Otherwise i can confirm some sort of strange behavior. 
A extensive test should be necessary.

These installation is running with Java 8 as well without any specific errors.

**Comment by StephanMa** [comment]
1) After an Import (CEI or Excel) the menu on the top shows the submenu from Publish (with cancel and ok button) and remove imported charter. But i am currently not able to reprocude it. If happens again, i will give another informations concerning this.
2) On the Main-Site, imported Fonds are not "clickable". Statistic are not updated.
3)  While Importing, every redirect to a new page must be confirmed 
![screenshot leave site](https://cloud.githubusercontent.com/assets/6735556/6920551/61a6cf00-d7bf-11e4-91af-3fc365785ff5.png)

**Comment by StephanMa** [comment]
Just  for your information:
eXist 3.0 is currently under construction. Scheduled Release should be around June 5, 2015.
See https://github.com/eXist-db/exist/milestones

Maybe we should wait for eXist 3.0 instead testing eXist 2.2

**Comment by GVogeler** [comment]
cfr. #379 #384

**Comment by StephanMa** [comment]
Upgrade to eXist 2.2 is ready for some testing.

I tried to upgrade directly to eXist 3.0 RC1 but unfortunately they broke the backwards compatibilty multiple times. So we have to rework mom-ca again...

After the release of eXist 3.0 i will directly rework my solution to upgrade to the latest release of eXist

**Comment by GVogeler** [comment]
moved to #589
