### ISSUE TITLE
Use cei:idno@id for atom:id if existing

### ISSUE THREAD

**Issue by icarus-eu** [icaruseu/mom-ca#245]
To enable the use of an atom:id that is different from the charters' signature at import-time, the `cei:idno@id` attribute should be used as identifier for the database.

-----

Current status:

The `cei:idno@id` attribute is currently completely ignored in the import process. For example, the following elements 

* `<cei:idno>DL_4231</cei:idno>`
* `<idno id="004401">DL_4231</idno>`
* `<cei:idno id="DL_4231">DL_4231</cei:idno>`

are all transformed to `<cei:idno id="DL_4231">DL_4231</cei:idno>` during the import process.

-----

Suggested functionality: 

1. On import, every charter is checked for an existing `cei:idno@id` *attribute*. If it is present, the content is used as the identifier in the database
2. If the attribute is missing, the *content* of the `cei:idno` element is used for this purpose, in addition of it functioning as "signature" of the charter (visible in the charter view).

-----

Problems:

* Is there currently a check whether or not the used data is unique inside the current fond / collection? If not, should this check exist?
* Is the `cei:idno@id` attribute used in some other function than solely as database identifier of the document?

-----

Example:

      <?xml version="1.0" encoding="UTF-8"?>
      <cei xmlns="http://www.monasterium.net/NS/cei">
         <teiHeader>
            <fileDesc>
               <titleStmt>
                  <title/>
               </titleStmt>
               <sourceDesc>
                  <p/>
               </sourceDesc>
            </fileDesc>
         </teiHeader>
         <text>
            <front>
               <div>
                  <head/>
                  <p/>
               </div>
            </front>
            <group>
               <text type="charter">
                  <body>
                     
                     <idno id="039400">DL_39250</idno>
                     <chDesc>
                        <issued>
                           <date value="12029999">1202</date>
                        </issued>
                        <witnessOrig>
                           <archIdentifier>
                              <arch>MNL</arch>
                           </archIdentifier>
                        </witnessOrig>
                     </chDesc>
                  </body>
                  <back/>
               </text>
               <text type="charter">
                  <body>
                     <idno id="004400">DL_4230</idno>
                     <chDesc>
                        <issued>
                           <date value="12229999">1222</date>
                        </issued>
                        <witnessOrig>
                           <archIdentifier>
                              <arch>MNL</arch>
                           </archIdentifier>
                        </witnessOrig>
                     </chDesc>
                  </body>
                  <back/>
               </text>
            </group>
         </text>
      </cei>

**Comment by GVogeler** [comment]
@Strec meint: welche Rolle spielt `cei:idno` anderweitig: Auf den ersten Blick wird hier und da sowohl cei:idno/text() als auch cei:idno/@id angesprochen. Ohne Doku muss da nochmal überall dort im Code nachgeschaut werden, wo cei:idno oder auch cei:idno/@id angesprochen wird, wie das dann weiter verwendet wird.

**Comment by GVogeler** [comment]
@yngwi sagt: Die Daten aus Ungarn verwenden eine "DL/DF Nummer" als Referenz. Diese sollte als `cei:idno` angezeigt werden. Sie ist aber nicht eindeutig und kann deshalb nicht als `atom:id` verwendet werden. Dafür haben die Daten eine "ISIS Nummer" (Arcanum interne Identifikationsnummer).

**Comment by GVogeler** [comment]
Auf Deutsch: `idno/text()` und `idno/@id` sollen beim Ingest einer CEI-Datei unterschiedlich sein können, damit aus `idno/@id` der Dateiname und die atom:id gebildet werden kann,während `idno/text()` angezeigt wird.
Es geht also darum, daß wir beim Import 1. die `atom:id` und den Dateinamen nicht aus `idno/text()` sondern aus `idno/@id` bilden und 2. danach `idno/@id` mit dem 
Wert aus `idno/text()` überschreiben.

**Comment by StephanMa** [comment]
Bei dem Importvorgang werden alle idno-Werte ausgelesen und für die Verarbeitung übergeben.
Wenn die ATOM-ID und der Dateiname gebildet wird, muss, wenn vorhanden, `idno/@id` herangezogen werden. Ist dieses nicht vorhanden, gilt wie bisher der normale `idno-Wert`.

Anpassungen müssen nach
https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/charters/service/xml-import.service.xml#L183
erfolgen.

Die Funktion `charter:insert-unique-idno` in `my/XRX/src/mom/app/charter/charter.xqm` setzt im nächsten Schritt dann `idno/@id auf den Wert von idno`.

Problematisch ist allerdings, dass für die Generierung der `atom:id` nicht die reine `idno`genommen wird, sondern eine bereinigte. Das bedeutet: Vor der Erzeugung des Dokumentes wird die `idno` noch auf die Eindeutigkeit hin geprüft. Ist dieses nicht der Fall, wird der `idno` noch eine Zahl (Häufigkeit des Auftretens) angehangen. Dadurch wird die `idno` nicht mehr im Ursprungszustand belassen. 
Meiner Meinung nach müsste die Eindeutigkeit der `idno` bereits im Validierungsschritt geprüft werden. Dort wird zZt. lediglich die Validität des Dokument an sich geprüft.

**Comment by GVogeler** [comment]
Bislang haben wir die Archive nicht dazu gezwungen, konsistente Daten zu liefern. Da die Monsterium-interne-ID ohnehin zwar sprechend aber nicht synchron zwingend synchron zu den Archivdaten ist, könnte man das Umschreiben also beibehalten.

**Comment by StephanMa** [comment]
Ich sehe grade, dass die @id beibehalten werden muss. Denn in einigen Bereichen wird diese Angabe dazu benutzt durch die Urkunden zu navigieren. Deshalb müssen die ID-Angaben aus dem Importvorgang vorhanden bleiben und dürfen **nicht** überschrieben werden.

**Comment by StephanMa** [comment]
Bei dem Importvorgang wird nun die `@ID` als Basis für die Bildung der Atom-ID und des Dateinamens verwendet. Im Anschluss an den Importvorgang wird `@ID` mit dem Wert aus `idno` überschrieben.

Etliche Module verwenden aber die `@ID` als Identifizierungsmerkmal für die Urkunden. An dieser Stelle wurde eine neue Funktionalität implementiert, die das letzte Token der Atom-ID zurück gibt. Dadurch ist der Zugriff gewährleistet. 

Das Verhalten wird nun getestet und anschließend commited

**Comment by yngwi** [comment]
Soweit ich sehe, funktionieren die Änderungen im Großen und Ganzen, es gibt aber noch folgende Probleme:

* Das `cei:idno@id` einer Urkunde, die beim Import einen anderslautenden `cei:idno/text()` Inhalt hatte, sieht seltsam aus: `15144_
__________` statt `15144`.
* MOM-Edit-2 lädt nicht wenn `cei:idno/text()` anders ist als `cei:idno@id`.

**Comment by GVogeler** [comment]
> * MOM-Edit-2 lädt nicht wenn `cei:idno/text()` anders ist als `cei:idno@id`.

Deshalb müßte `cei:idno@id` durch `cei:idno/text()` überschrieben werden 
- und die Inventar-Nummer bei den ungarischen Daten nicht nur in 
`cei:idno@id` sondern auch als `cei:altIdentifier` angegeben werden.

Oder?

**Comment by StephanMa** [comment]
Bei dem Datenimport von cei-Dateien wird idno/@id in die Atom-Tag übernommen und anschließend von idno überschrieben. Für den Zugriff auf die Urkunden wird nun nicht mehr id oder idno verwendet, sondern das letzte Token der Atom-id. Ein Unterschied in den Urkunden in dem Attribut id und idno sollte es nicht geben. Für den Zugriff auf die Urkunde ist altIdentifier unerheblich.

Das Problem liegt wahrscheinlich daran, dass @id != idno ist, was eigentlich nach dem Import nicht sein sollte. 

Oder habe ich hier noch was falsch verstanden?

Viele Grüße 
Stephan 

Von meinem iPhone gesendet

**Comment by icarus-eu** [comment]
Hier meine Gedanken zum Thema. Erst nochmal die Hintergründe, dann die konkreten Überlegungen.

---

Der abstrahierte Grund für diese Änderungen ist ja, dass Archiv-Signaturen (also Hilfswissenschaftlich gesprochen) nicht direkt als eindeutiges Identifizierungskriterium herangezogen werden können, da sie oft nicht nur für ein Objekt in unserem Sinne stehen, sondern für etwas, das letztlich im Archiv historisch gewachsen ist. Im Ungarischen Nationalarchiv (aber z.B. auch bei der Allgemeinen Urkundenreihe im Österreichischen Staatsarchiv) steht eine Signatur gelegentlich für mehrere Dokumente, die bei uns als jeweils separate Urkunden gelten.

Die Ungarn haben nun für sich die Lösung gewählt, zusätzlich zur Signatur (in CEI das `cei:idno` Element) eine eindeutige Nummer (die sogenannte _ISIS-Nummer_) zu vergeben, die individuelle Urkunden nach dem gängigen Begriff identifiziert. Diese wird in ihrer Datenbank verwendet, um die URIs für die Urkunden zu generieren. Nach außen hin für Benutzer relevant ist aber weiter ausschließlich die in den 1870er Jahren entstandene Signatur, in Ungarn _DL/DF-Nummer_ genannt. 

Die ISIS-Nummer scheint im Gegensatz zur DL/DF-Nummer nirgends auf, die Ungarn haben, anders als MOM-CA, keine sprechende URI, mit dem die Urkunden identifiziert werden.

Das Problem für MOM-CA war jetzt, dass üblicherweise (also wenn unter direktem Einfluss von ICARUS digitalisiert wurde), im Fall von nicht eindeutigen Signaturen einfach eine "gebastelt" wurde, zum Beispiel indem ein Buchstabe angehängt wurde (z.B. 1234-A, 1234-B). Dies ist etwa in Klöstern, in denen bis dato nur analoge Findmittel vorhanden waren bzw. zusätzliche Zählungsweisen in Urkundeneditionen wie etwa einem Niederösterreichischen Urkundenbuch geläufig sind, kein großes Problem. Die Ungarn haben sich aber spezifisch gewünscht, dass als Signatur die unveränderte DL/DF-Nummer verwendet wird, was die bisherige Lösung verunmöglicht hat.

-----

Konkret bedeutet das für mich:

`atom:id` ist ein technisches, `cei:idno` und `cei:idno/@id` aufgrund der Zugehörigkeit zum CEI-Schmea ein hilfswissenschaftliches Identifikationsmerkmal. Die Benutzer interessiert vor allem letzteres. Trotzdem wollten wir aber die atom:id sprechend haben, deshalb ergab die Verknüpfung mit cei:idno Sinn. Es wäre wohl vernünftig gewesen, die atom:id so zu gestalten, dass sie die cei:idno unmodifiziert übernehmen kann und trotzdem eindeutig bleibt (etwa so mithilfe einer Unix Epoch: `tag:www.monasterium.net,2011:/charter/AT-OeSta-HHStA/AUR/234/1435914728`). Dafür ist es aber wohl zu spät. 

Es gibt nun in meinen Augen (für die Zukunft) zwei Möglichkeiten:

1. Atom:id wird völlig von cei:idno und cei:idno/@id entkoppelt und kann lauten wie auch immer er will. Hier würde ich letztlich die Archive entscheiden lassen, wie im Fall der Ungarn. cei:idno und cei:idno/@id blieben hier identisch.

2. atom:id und cei:idno/@id bleiben aneinander gekoppelt und cei:idno spielt nur mehr die Rolle der Signatur für Benutzer (sortieren, listen etc.). Beim Import müsste dann bei nicht Eindeutigkeiten zuerst cei:idno/@id generiert werden, z.B. einfach mit dem Nummerieren aller Vorkommnisse, also _234-1_, _234-2_ etc. In Kombination mit Archiv und Bestand wäre das ja dann eindeutig. Trotzdem bliebe die atom:id sprechend.

Beide Lösungen haben zur Konsequenz, dass der Code dahingehend modifiziert werden muss, dass er nur mehr die betreffenden Elemente dort verwendet, wo sie angebracht sind, vor allem also nie mehr cei:idno wo die Urkunde im System identifiziert werden muss.

Was meint ihr?

**Comment by GVogeler** [comment]
Ich glaube die theoretischen Überlegungen sind gar nicht mehr nötig:

@StephanMa, Daniel hat eine Urkunde mit `idno@id` != `idno/text()` 
importiert und dabei ist 
http://dev.monasterium.net/mom/HU-MFL/DLCLBC/15144_%0A__________/imported-charter 
herausgekommen. Also das Problem 1 dieses Threads.

@icaru-eu (=Daniel), kannst Du dem Stephan einfach mal die CEI-Quelle 
dieses Ingests zur Verfügung stellen, damit er überprüfen kann, warum 
genau dabei die komische atom:id entstanden ist?

Viele Grüße

G


Am 03.07.2015 um 11:27 schrieb ICARUS Admin:

**Comment by GVogeler** [comment]
PS: Die Import-Quelle ist vermutlich

http://dev.monasterium.net/mom/HU-MFL/DLCLBC/recently-imported-file

oder?

Am 03.07.2015 um 11:27 schrieb ICARUS Admin:

**Comment by icarus-eu** [comment]
[Ergebnis](http://dev.monasterium.net/mom/HU-MOL/DLDF/12345/charter)

Importquelle:

```xml

<?xml version="1.0" encoding="utf-8"?>
<cei xmlns="http://www.monasterium.net/NS/cei">
  <teiHeader>
    <fileDesc>
      <titleStmt>
        <title />
      </titleStmt>
      <sourceDesc>
        <p />
      </sourceDesc>
    </fileDesc>
  </teiHeader>
  <text>
    <front>
      <div>
        <head />
        <p />
      </div>
    </front>
    <group>
      <text type="charter">
        <!-- Charter http://archives.hungaricana.hu/en/charters/172143 ; wrong ISIS Number because I couldn't find it -->
        <front />
        <body>
          <idno id="12345">15144 
          <!-- idno/text() = DL/DF Number; idno@id = ISIS Number --></idno>
          <chDesc>
            <abstract>Hwnyad-i László besztercei comes, királyi lovászmester kötelezi magát, hogy apjának írásbeli meghagyása alapján Eleskew várát, amely, jelenleg Ankelreyther Nabogodonosor kezén van, három éven belül visszaszerzi annak a kezeiből és visszaadja Rozgon-i Sebestyénnek, vagy egy másik hozzá hasonló és vele egyenértékű várat ad neki, vagy 4.000 arany forintot fizet Sebestyénnek; ha ezt nem teljesítené, az apjától adott oklevélben foglalt kötelezettségekben marad el. - A szöveg alatt veresszínű pecsét töredékeivel. 
            <issuer>Hunyadi László besztrecei ispán 
            <!-- issuer = Issuer of charter --></issuer>
            <!-- Abstract --></abstract>
            <issued>
              <date value="14570223">1457-02-23 
              <!-- date/text() = literal date, can be anything; date/value = exact date, needs to be 8 digits yyyymmdd, unknown parts need to be filled with number 9: 14570299 for February 1457 (consider using cei:dateRange) --></date>
              <placeName>Strigonii Esztergom Esztergom m 
              <!-- Place of dating --></placeName>
            </issued>
            <witnessOrig>
              <traditioForm>Eredeti 
              <!-- Survival form --></traditioForm>
              <archIdentifier>
                <arch>Kincstári levéltárból (E) 
                <!-- Name of the archive --></arch>
                <ref target="http://archives.hungaricana.hu/en/charters/172143" />
                <!-- Link to the charter in the hungaricana website -->
              </archIdentifier>
              <figure n="DL_015144DL_015144_orig_r">
                <graphic url="http://images.monasterium.net/test/HU-MFL/DIPLOMATIKAI%20LEV%C3%89LT%C3%81R_Csal%C3%A1di%20lev%C3%A9lt%C3%A1rak_Becsky%20csal%C3%A1d/DL_015144DL_015144_orig_r.jpg" n="thumbnail" />
              </figure>
              <figure n="DL_015144DL_015144_orig_v">
                <graphic url="http://images.monasterium.net/test/HU-MFL/DIPLOMATIKAI%20LEV%C3%89LT%C3%81R_Csal%C3%A1di%20lev%C3%A9lt%C3%A1rak_Becsky%20csal%C3%A1d/DL_015144DL_015144_orig_vjpg" n="thumbnail" />
              </figure>
            </witnessOrig>
            <lang_MOM>Latin 
            <!-- Language --></lang_MOM>
          </chDesc>
        </body>
        <back />
      </text>
    </group>
  </text>
</cei>
```

**Comment by StephanMa** [comment]
Ich schaue mir das mal genau an. Ich verwende dafür dann erstmal die Importdatei vom testserver. 
 
Viele Grüße 
Stephan

Von meinem iPhone gesendet
