### ISSUE TITLE
Add (de)select Button to fonds in beta-search

### ISSUE THREAD

**Issue by yngwi** [icaruseu/mom-ca#256]
In the [beta-search results page](http://monasterium.net/mom/search2) there should be the possibility to (de)select all fonds similar to the categories (see image attachment)

-----

![de-select](https://cloud.githubusercontent.com/assets/963440/7611992/3ff22158-f988-11e4-95e2-def5c46d825d.PNG)

**Comment by GVogeler** [comment]
... and the same for the group of collections further down in the list ...

**Comment by GVogeler** [comment]
In the current state of the code (deployed on dev.monasterium.net) search2 doesn't evaluate the deselection: e.g.: Search http://www.monasterium.net/mom/search2?q=Drosendorf&option=and&img=&annotations=&sort=date&categories=&context= , deselect all archival fonds, click on arrow in any section (=execute search) leads to http://www.monasterium.net/mom/search2?q=Drosendorf&option=and&img=&annotations=&sort=date&categories=%40reg%2Ccei%3Aabstract%2Ccei%3AplaceName%2Ccei%3Atenor%2Ccei%3ApersName%2Ccei%3Anote%2Ccei%3AdivNotes%2Ccei%3AgeogName%2Ccei%3AsealDesc%2Ccei%3AwitnessOrig%2Ccei%3AquoteOriginaldatierung%2Ccei%3Aauth%2Ccei%3Alegend&context=AT-AWMK%3BAsparnOFMConv%2CAT-DASP%3BUrkunden%2CAT-HHStA%3BGarsPf%2CAT-HHStA%3BMitterndorfPf%2CAT-HHStA%3BSbgE%2CAT-HHStA%3BStBernhardOCist%2CAT-HHStA%3BWNOP%2CAT-HKA%3BUrkunden%2CAT-StaABdW%3BUrkunden%2CAT-StaAR%3BUrkDominikanerkloster%2CAT-StaAR%3BUrkundenreihe%2CAT-StaAWei%3BUrkunden%2CAT-StaAZ%3BUrkunden%2CAT-StiAA%3BUrkunden%2CAT-StiAG%3BGoettweigOSB%2CAT-StiAGe%3BUrkunden%2CAT-StiAH%3BHeiligenkreuzOCist%2CAT-StiAHe%3BDuernsteinOSCl%2CAT-StiAHe%3BHerzogenburgCanReg%2CAT-StiAK%3BStDorotheaCanReg%2CAT-StiAKr%3BKremsmuensterOSB%2CAT-StiAL%3BLambachOSB%2CAT-StiALi%3BLilienfeldOCist%2CAT-StiAM%3BMelkOSB%2CAT-StiAMB%3BMbOSB%2CAT-StiASch%3BSchlierbachOCist%2CAT-StiAScho%3BSchottenOSB%2CAT-StiASei%3BSeitenstettenOSB%2CAT-StiAZ%3BUrkunden%2CAT-WStLA%3BHAUrk%2CAT-WStLA%3BHAUrkAbschr%2CCZ-NA%3BACK%2CDE-BayHStA%3BHUPassau%2CDE-BayHStA%3BPassauDomkapitel%2CDE-StABa%3BLangheim%2CAFM%2CFreisBm%2CKlosterStBernhard%2COOEUB%2CSaeuOCist%2CStPCanReg%2CUrkundenMaehren which is identical. Reasons to be investigated.

**Comment by strec** [comment]
As far as I know, that is a feature, not a bug.
See here:
https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/search/search.xqm#L82
and here:
https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/search/search.xqm#L177
If you deselect all checkboxes of a search filter group, then you would always end up with zero search results. No point in searching, then. Thus there are the above-mentioned checks in place.

**Comment by GVogeler** [comment]
nope, if you deselect all archival fonds but select all collection you should get an result. => we have to extend `search:context`in https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/search/search.xqm#L177 to handle this.

**Comment by strec** [comment]
The "(de-)select all" button now became the "invert selection" button, inverting all checkboxes of the corresponding section. This is even better, I think.
