### ISSUE TITLE
Lucene synax for matching precision is not supported by paging of search hits

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#267]
http://monasterium.net/mom/search?q=Rozmberka~0.8&sort=date&arch= gives good results but http://monasterium.net/mom/search?null=&sort=date&arch=&q=Rozmberka~0.8&block=2 returns no results any more
search2 seems to work: http://monasterium.net/mom/search2?null=&sort=date&q=rozmberga~0.8&img=&context=&categories=&annotations=&option=and&block=2

**Comment by maburg** [comment]
Cannot be confirmed. Both searches work well!
