### ISSUE TITLE
Suche muß `atom:id` mit in Suchindex aufnehmen?

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#269]
follow-up zu #245

**Comment by StephanMa** [comment]
Wenn bei dem CEI-Import die Atom-Tag aus dem Attribut `@id` gebildet und dieses Attribut im nächsten Schritt überschrieben wird, lässt sich die ursprüngliche ID nicht in der Suche mit einbeziehen. 
Mit #245 wurde eh die ID durch den letzten Token der AtomTag verwendet, sodass die ID nicht mehr relevant für die Suche ist. Vielmehr muss die Charter-ID aus dem AtomTag extrahiert werden.

**Comment by GVogeler** [comment]
Ich denke, wir sollten in die Suche nur Angaben aufnehmen, die der Benutzer auch in der Urkundenansicht angezeigt bekommen kann. Wenn bei der Umwandlung von `idno/@id` Informationen in die atom:id geschrieben und dann die `idno/@id` überschrieben wird, die Information aus dem Attribut aber aussagekräftig ist, dann sollen die Archivare sich überlegen, wo man die Information in den Daten ablegen kann (z.B. `cei:altidentifier`).
