### ISSUE TITLE
EditMOM3 needs a mechanisms to check if existing charter is covered by template

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#275]
(part of #43 )
EditMOM3 is currently only designed to handle freshly created documents. In `mycollection.xqm` the function `my-collection-charter-new-empty` uses a template to create the new empty charter which contains all the elements necessary for the binding.
(see https://github.com/icaruseu/mom-ca/wiki/Code-structure-of-the-editor )
If we want to use EditMOM3 for existing charters, we have to make sure that the document is conformant to the expected binding or make EditMOM3 more generic (i.e. reduce the minimal template and create a meachism to add new visualxml elements ( #35 ) .

The documents stored in MOM-CA were created without this template, so they could:

* use additional elements (#35)
* don't use a required element
* use the elements in a nesting not included in EditMOM3 (#276)

Possible solutions?

1. create a template "on the fly" merging the data of the original charter and the default template
2. create a template "covering all" possibilities of markup (might need a more restricted schema to ensure that)
3. build EditMOM3 more generically without a template

**Comment by GVogeler** [comment]
see #296

**Comment by GVogeler** [comment]
Vorschlag von @StephanMa : 
Man müsste den Editor vollständig abändern:
Die Bindings für die CEI-Felder müssten alle dynamisch geladen werden.
Dieses ist für sich erst mal nicht das Problem. Schwieriger wird die Tatsache, wie die Textboxen automatisiert angeordnet werden sollen.
Ich habe zum Test bereits eine Funktion geschrieben, die die Bindings für die Textfelder automatisiert erzeugt. Das funktioniert auch schon soweit.
Alternativ könnte ich mir vorstellen, dass alle zusätzlichen Felder, die bis dato noch nicht im Editor sind, in einer separaten Tab-Page eingestellt werden.

**Comment by GVogeler** [comment]
Prinzipiell kann man ja sagen: jedes Element, das nicht von der Template abgefangen wird, kann ein visualxml-Control werden.
Dann ist die einfachste zu lösende Frage: in welchem Tab soll es stehen?

Dafür wäre es am praktischsten, wenn die Tabs mit XML-Strukturen korrespondieren würden, also jeweils einen gemeinsamen Knoten repräsentieren. Das ist der Fall bei "Anhang" (=cei:back), Transkription (=cei:tenor), "Kopiale Überlieferung" (=cei:witListPar), Original (=cei:witnessOrig). Bei "Regest", "Bemerkungen" und "Quelle" ist es schwieriger, obwohl ich mir auch XPath-Ausdrücke ausdenken könnte, die das abbilden: Regest=cei:chDesc/(cei:abstract|cei:issued)|cei:idno, Bemerkungen=cei:chDesc/cei:*[not(name()='abstract' or name()='issued' or name()='witnessOrig' or name()='witListPar')], Quelle=cei::sourceDescRegest|cei:sourceDescVolltext.

Vom Schema her, sieht das so aus, als ob es alles abfangen würde. Ob das a) in den Test eingebaut werden kann und b) die reale Welt abbildet ist eine andere Frage :-)

Die nächste zu lösende Frage wäre dann: Wo kommen die "not-in-template"-visualxml-controls dann zu stehen? Könnte man sie einfach in der Reihenfolge ihres Vorkommens anhängen?

**Comment by StephanMa** [comment]
Ich muss verifizieren, inwiefern die automatisierte Generierung von Controlls vom Compiler angenommen wird. Wahrscheinlich wird es an dieser Stelle das größte Problem geben. 
Ich teste das aber einfach mal aus und werde die Ergebnisse dann als Ausgangsbasis für weiterführende Überlegungen verwenden.

**Comment by StephanMa** [comment]
Wie befürchtet, ist es nicht möglich, die jetzige Architektur des Editors dynamisch zu gestallten.
Bei dem Kompiliervorgang müssen die Angaben über die Bindings bereits im Code vorhanden sein, d.h. eine Anpassung des Editors zur Laufzeit ist über diesem Weg nicht möglich.

**Comment by GVogeler** [comment]
Dann brauchen wir unter den derzeitigen Bedinungen eine "Catch-All-Template" (Lösung 2 von oben), oder?

**Comment by StephanMa** [comment]
Wir benötigen die Möglichkeit drei ("EditMOM3 more generically without a template"). Der Editor muss so aufgebaut sein wie der VdUEditor. Dieser generiert das Frontend "on-the-fly", im Gegensatz zu dem EditMOM3. Ein Template würde die Problematik nicht beheben, da die Bindings und die Anbindung an die Textcontrols alle statisch sind. Auf Grund der Beschaffenheit des Editors sehe ich da auch relativ wenig Spielraum außer einer vollständigen Neuprogrammierung.

**Comment by StephanMa** [comment]
Das Problem wurde, wie folgt, gelöst:

Der Editor wird zukünftig mehrere Stufen durchlaufen.
1) Ist in einer bestehenden Urkunde nur ein geringes Set an Feldern vorhanden, wird der Editor automatisiert sämtliche Felder aus dem Template in die Urkunde integrieren, sodass der Editor ordnungsgemäß funktioniert.
2) Sind in einer Urkunde mehr Felder vorhanden als im Template, werden diese Felder in einem gesonderten Tab "unrecognized" zur Bearbeitung angeboten. Felder, die bereits mehrfach innerhalb der Urkunde deklariert worden sind (z.B. cei:graphic ), werden als Mehrfachvorkommen (<xrx:repeat>) behandelt. Es erfolgt keine Unterscheidung woher ein Feld stammt ("cei:listBibl, cei:listBiblRegest", etc.).

Während der Kompilierprozess die <xrx>-Tags in <div>s umsetzt, wird nun zur Laufzeit die fehlende Bindings und Controls in "kompilierter" Form eingeschleust, d.h. es werden zusätzliche Tags ergänzt. 
Danach können alle Felder wie gewohnt bearbeitet werden.

Derzeit erfolgt eine Optimierung des Sourcecodes und weitere Tests (Laufzeitverhalten, etc.). Im Anschluss erfolgt der Commit.

![editmom3 - new](https://cloud.githubusercontent.com/assets/6735556/8955264/629e6d66-35eb-11e5-9ecc-f3167c7d9a1b.png)

**Comment by StephanMa** [comment]
After further Development, the Editor is build totally dynamically.

The new file `mycollection-charter-editor.template.xml` defines which fields are allowed to display inside the Editor. It contains the name of the individual Field (including namespace, e.g. `"cei:date"`), the parent Field, the expected TabPage and some other configuration-parameters.
    `<id>` contains the XML-Node as a key : string
    `<mult_occurence>` triggers if `<xrx:repeat>` or not : bool
    `<target_field>` Just important, if `<mult_occurence>` is true. Contains Name of Childnode for Textarea : string
    `<tab_page>` contains the number of the Tabpage to which the Node belongs to : string
    `<active>` contains the current status of the Node : bool
    `<message>` contains the field which is important for the i18n-Module ("self" / "target") : string
    `<groups>` contains the groups for which the Field should be enabled : element group with string



You can group some fields inside the same tabPage inside the File `mycollection-charter-editor-fieldset.template.xml`.    

It contains individual Declarations of Fieldsets
        `<tab_page>` contains the TabPage which this Fieldset belongs to
        `<legend>` contains the Heading for this as a key-string for the i18n-module
        `<fields>` contains every Field from this TabPage which belongs to this Fieldset

To add a Field as an editable Field to the Editor, you just habe to add an entry to the editor-template. You can make those changes "on-the-fly". There is no need to recompile it at all ( #35 ).

Tests are currently running. After a successfull test, PR will follow.

**Comment by StephanMa** [comment]
Should be fixed with #340

**Comment by GVogeler** [comment]
closed with #330
