### ISSUE TITLE
EditMOM3 template has to fit to existing data

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#296]
currently the editor controls in [EditMOM3](https://github.com/icaruseu/mom-ca/wiki/Some-terminology) are exclusively defined by the bindings in https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/collection/template/mycollection-charter.template.xml . The documents stored in MOM-CA were created without this template, so they could:
* use additional elements (#35)
* don't use a required element
* use the elements in a nesting not included in EditMOM3 (#276)

Possible solutions?
* create a template "on the fly" merging the data of the original charter and the default template
* create a template "covering all" possibilities of markup (might need a more restricted schema to ensure that)
* build EditMOM3 more generically without a template

**Comment by StephanMa** [comment]
Is done by Issue #43 

If a given Charter doesn't fit the minimal amount of CEI-Fields for the Editor, all necessary fields are added on  startup of the Editor. If additional Fields are added inside the template/Editor, the Fields are added dynamically to the Charter. This Feature is just called if the Charter is edited.

**Comment by GVogeler** [comment]
Discussion moved to #275

**Comment by StephanMa** [comment]
Should be fixed with #340
