### ISSUE TITLE
To be verified: EditMOM3 doesn't get Attributes from JS

### ISSUE THREAD

**Issue by StephanMa** [icaruseu/mom-ca#300]
In EditMOM3 the Field cei:lang_MOM is editable inside the Tab-Page "Bemerkungen".

The CEI.xsd includes a Definition for this field. mom_LANG is also available inside chDesc, which is confirmed for my example. But the attributes aren't listed as expected.

Currently i am not able to figure out why the attributes aren't listed yet.

Any Suggestions?

Relevant Part: 
https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/core/app/xrx/js/codemirror.mode.visualxml.js#L154

https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/cei/xsd/cei.xsd#L1063

**Comment by StephanMa** [comment]
The Editor sometimes prohibites to read attributes from the Node
<xrx:visualxml attributes="no" elements="no" ref="">
This was the pattern for the recreation of the editor. Changed statement! Now all attributes from the "unregocnized"-Tab are displayed correctly!

Issue can be closed

**Comment by GVogeler** [comment]
The rationale behind this is that some attributes have a purly technical 
function and shouldn't be edited by the user. In VdUEdit these rules are 
defined in the cei.xsd in application-notes if I remember correctly.

Am 30.07.2015 um 10:07 schrieb Stephan M:
