### ISSUE TITLE
`cei:tenor/cei:note` isn't displayed in charter preview/single charter view

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#316]
reports Antonella Ambrosio

**Comment by StephanMa** [comment]
I can not confirm this in general.
I added "<cei:note>Das ist ein Note</cei:note>" to <cei:tenor> and this phrase is displayed inside the single charter view.

Can she provide us with some example?

**Comment by GVogeler** [comment]
in my-charter (https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/charter/widget/my-charter.widget.xml) the footnote is displayed as inline text:
![footnoteinline](https://cloud.githubusercontent.com/assets/324006/9995247/782a78bc-6081-11e5-8094-e5468bf6cff8.png)
This behaviour should be replaced by a display similar to the single charter view.

**Comment by GVogeler** [comment]
cfr. #180

**Comment by GVogeler** [comment]
other example: http://www.monasterium.net/mom/SSRQ_AR_AI_1_Nr_1/SSRQ_Appenzell_2/charter#P1_fnn4

**Comment by GVogeler** [comment]
ToDo: check handling of `cei:divNotes/cei:note` to `cei2html.xsl` in charter-app.

**Comment by StephanMa** [comment]
There are two different problems:

1) in cei2html.xsl the template match for "diplomaticAnalysis" isn't triggered because its just fired if there is any text. But it should also be triggered if lang_MOM or something beneath it is available.

2) in commit #420 ab381a49e there was a change introduced
https://github.com/icaruseu/mom-ca/blob/ab381a49e13d1d608d2033cde839dce166051a6f/my/XRX/src/mom/app/charter/xsl/cei2html.xsl#L518

is an ambiguous rule with the next rule concerning   <xsl:template match="cei:ref[@type='bibliography']">, so an error occurs

**Comment by GVogeler** [comment]
on 2): I currently don't see any reasons why we need the `<xsl:template match="cei:ref[@type='bibliography']">` template which actually does not do anything.

**Comment by GVogeler** [comment]
on 1) ad `cei:divNotes/cei:note` is part of `cei:back` the `<xsl:template match="xhtml:insert-diplomaticAnalysis">` (https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/charter/xsl/cei2html.xsl#L178) should select by all the existence of all elements which are displayed in this area (see all `xsl:if` and `xsl:template` in https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/charter/xsl/cei2html.xsl#L1224 )

**Comment by GVogeler** [comment]
on 2): `<xsl:template match="cei:ref[@type='bibliography'] handles special encoding in www.monasterium.net/mom/SSRQ_AR_AI_1_Nr_1/collection where data comes from a source which used  the `@type` to handle other functionality. See #579 for a solution

**Comment by GVogeler** [comment]
current state of code has necessary conditions for 1) (https://github.com/icaruseu/mom-ca/blob/3a3ff135e75e0c93caa297c8f6219f44abb57dc0/my/XRX/src/mom/app/charter/xsl/cei2html.xsl#L260). No errors are reported any more.
