### ISSUE TITLE
shared documents aren't rendered correctly in EditMOM3

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#322]
![zwischenablage02](https://cloud.githubusercontent.com/assets/324006/10044781/df9a39e2-61fd-11e5-906f-61b5d2c37238.png)
(reported by Antonella Ambrosio)

![zwischenablage02](https://cloud.githubusercontent.com/assets/324006/10044813/0b8f6a7c-61fe-11e5-9cfc-ff0db6b60772.png)
(reported by `georg.vogeler@uni-graz.at`)

Both documents can be edited without problems by the original owner

**Comment by StephanMa** [comment]
It looks like that the Editor is not able to load the Charter ($entry). I suggest that there is a problem resolving the correct $base-collection. If you try to load the Charter via Illurk, it works!

EditMOM3 shoud choose the correct collection for loading the Charter

**Comment by GVogeler** [comment]
closed with #341
