### ISSUE TITLE
Customized EditMOM3 (MOMAthon) is not able to save charters

### ISSUE THREAD

**Issue by StephanMa** [icaruseu/mom-ca#362]
There is no specific hint for this problem in the eXist-Logfiles.
So i had done some unspecific tests:

Testcase:
1) Ping local server with 4092 bytes all the time
2) Get a high server load while creating a lot of new sessions
let $test := for $i in (1 to 300000000)
    return session:create()

Result:
Sometimes the Editor is not able to save done changes. I get the Error "Failed to load Save-script".

It can be possible that the high sever load or many server requests are one possibility for this issue. 
Unfortunately it is not reproducable all the time.

**Comment by GVogeler** [comment]
Still an issue?

**Comment by StephanMa** [comment]
Haven't had the error since then. 
May be closed and reopened if the error occures again...
