### ISSUE TITLE
Save-Error when adding whitespace between mark up

### ISSUE THREAD

**Issue by StephanMa** [icaruseu/mom-ca#364]
Reported via Email

> 2) Eine der Ursachen, die bei MOM-Ca die Fehlermeldung "Failed to save changes" auslöst, ist mit Sicherheit die Präsenz eines Leerzeichens zwischen dem Endtag einer Markierung und dem Anfangstag der folgenden Markierung, und zwar ganz unabhängig von der Art der Markierungen.
> Beispielsweise erscheint die Fehlermeldung bei der Mehrfachmarkierung eines Personennamens mit dazwischenliegendem Leerzeichen: »Ursonem« »Mastru«. Die Fehlermeldung verschwindet, sobald das Leerzeichen beseitigt wird, umd Mom-Ca speichert ohne Probleme. Wenn ich die Seite aber einfach neu lade, um das Problem zu beheben, eliminiert Mom-Ca das Leerzeichen von allein und speichert im Folgenden normal. Wenn ich also ein Leerzeichen zwischen Ursonem und Mastru benötige, muss ich dies innerhalb einer der Tags einfügen, beispielsweise am Ende von Ursonem:
> »Ursonem «»Mastru«.

I can confirm that this error is reproducable. Maybe its some kind of validation error. 
Should be analyzed with a high priority

**Comment by StephanMa** [comment]
The entire charter was submitted correctly.

But i could trace the Error to the Save-Service. 
The atom:put-Command is not able to save the Charter.

Hoepfully i will be able to pinpoint the error more detailed...

**Comment by StephanMa** [comment]
There are two different problems causing this Error...
1) eXist has different types of handling whitespaces while saving data. You can choose the right one inside the conf.xml. The current setting was, that all whitespaces inside mixed content should be supressed (Attribute `preserve-whitespace-mixed-content = "false"`). I changed it on my Maschine to "yes" and it works. Now you are able to have a whitespace between two tags.

2) The changes were written to disk but the Check-Mechanism (made by jan) compared the Version with whitespaces against the written Version without whitespaces. So the comparison has to fail and the Errormessage occurs. Unfortunately the changes were written. But without the added whitespaces

Solution: 
The `conf.xml` has to be changed. The attribute of `preserve-whitespace-mixed-content` has to be set to "yes". After a restart of the Server, all whitespaces are saved.

**Comment by StephanMa** [comment]
http://exist.2174344.n4.nabble.com/Whitespace-handling-using-transform-td4665182.html

**Comment by GVogeler** [comment]
Cfr https://github.com/eXist-db/exist/pull/548#issuecomment-174277998 for eXist internal discussion
