### ISSUE TITLE
Im Excel Import Workflow "Urkunden überschreiben" checken, Systemmeldungen sind nicht konsistent

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#37]

**Comment by strec** [comment]
Inwiefern "nicht konsistent"?

**Comment by GVogeler** [comment]
From: Karl Heinz 
Sent: Sonntag, 29. März 2015 20:43
To: Bernhard Strecker
Cc: Georg Vogeler; Daniel Jeller
Subject: AW: [mom-ca] Im Excel Import Workflow "Urkunden überschreiben" checken, Systemmeldungen sind nicht konsistent (#37)

Die Probleme lassen sich grob in zwei große Bereiche gliedern, nämlich Lokalisierung und Verständlichkeit.

Wenn Fehler angezeigt werden, dann geschieht dies bei Excel oder XML-Dateien unter Angabe der Zeilen- bzw. Spaltennummern. Diese Angaben sagen aber so gut wie nichts über den Fehlerort aus. Es wird z.B. eine Zeile 240 als Ort angegeben, obwohl das Quelldokument nur 50 Zeilen hat. Wobei natürlich nicht klar ist, was eigentlich die Grundlage der Zuordnung ist, denn eine XML Datei wird, je nach Editor, unterschiedlich strukturiert (txt, notepad,  notepad++, div. xml Editoren). Es wäre schon viel geholfen, wenn man den Fehler eindeutig lokalisieren könnte, dann kommt man schon drauf, was falsch sein könnte, auch wenn die Meldung selber für Laien nicht verständlich ist.

Der Zweite Bereich ist die Verständlichkeit der Meldung. Ich habe Dir vier alte Screenshots zur Verdeutlichung angehängt.  Inzwischen weiß ich, auf was ich bei dieser Art von Meldung achten muss, allerdings nicht wegen der Meldung selbst. Hier müsste eigentlich stehen: "Bei der Datumsangabe fehlt eine Stelle" oder etwas in dieser Richtung. Wir müssen uns vor Augen halten, dass wir ja anstreben, den Uploadprozess in Zukunft dezentral von jedem Archiv selbst durchführen zu lassen. Wenn ein Archivar, dessen EDV-Horizont sich normalerweise mit Kursiv- oder Fettsetzungen in Word erschöpft, solche oder ähnliche Fehlermeldungen sieht, dann wird sich der Elan der Kollegen in Grenzen halten.

Da wir gerade jetzt gerade keine Bestände zum Import haben, kann ich Dir leider nichts Aktuelles liefern, allerdings wird im Laufe des nächsten Monats wahrscheinlich etwas anfallen. Sollte sich etwas ergeben, dann schicke ich Dir die Screenshots als Dokumentation

----

Daniel Jeller:

zu Karls Mail kann ich noch anmerkend sagen (auch zur Aufklärung von Karl): die Fehlermeldungen beziehen sich, soweit ich nicht falsch liege, auf die XML Datei, die das Import-Tool aus der Excel Datei erzeugt und dann validiert. Die Meldung stammt im Allgemeinen (mir ist nicht bekannt, ob hier noch "Übersetzungen" eingebaut wurden) direkt vom XML-Validator und kommt in Ähnlicher Formulierung auch, wenn man den Code z.B. in Oxygen validieren würde. Das Data Preparation Tool vom Archives Portal Europe macht das zum Beispiel genauso.

Die Frage ist, wie lassen sich diese Meldungen vernünftiger gestalten. Der Validator z.B. hat ja keine Ahung von der Excel Tabelle, die hat er ja nie gesehen...
