### ISSUE TITLE
access restriction problem with shared charters in EditMOM3

### ISSUE THREAD

**Issue by digsc** [icaruseu/mom-ca#370]
confer mailing list

**Comment by GVogeler** [comment]
shared charters can be edited by any user who has the appropriate edit-URL

**Comment by icarus-eu** [comment]
The current version of the  fix was merged with Pull Request #552 but I'm not sure the popup is correctly translateable. @JBigalke, could you comment on this?

**Comment by GVogeler** [comment]
@yngwi : after triggering an update of i18n-messages via http://monasterium.net/mom/translate http://monasterium.net/mom/translate?lang=deu&catalog=all&only-untranslated=false&key=&q=permission&id= gives you the user interface for translation into German.

**Comment by yngwi** [comment]
Learning something new every day 👌

**Comment by GVogeler** [comment]
See https://github.com/icaruseu/mom-ca/wiki/i18n-environment as documentation for the future :-)
