### ISSUE TITLE
cei:listBiblFaksimile has wrong i18n key in EditMOM3

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#380]
`<cei:listBiblFaksimile>` is linked to the i18n:message "cei_diplomaticAnalysis" instead of "cei_listBiblFaksimile". In /app/cei/xsd/cei.xsd the `appinfo@source="EditVDU"` contains the correct reference. Where does EditMOM3 get's it's i18n-links from?

**Comment by StephanMa** [comment]
Its not really a bug at all.

You can configure the i18n-Message by choosing the i18n target, e.g.

https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/collection/template/mycollection-charter-editor.template.xml#L480

changing the line to "self" should to the trick

**Comment by StephanMa** [comment]
I changed it on the live-server

**Comment by GVogeler** [comment]
Thanks! Commit for the repository is on it's way.
