### ISSUE TITLE
EditMOM3: attributes of cei:figure aren't displayed

### ISSUE THREAD

**Issue by StephanMa** [icaruseu/mom-ca#383]
Try to edit a charter and change cei:figure (even cei:graphic isn't displayed as well!), you don't get an attribute displayed on the right site.
But otherwise an empy TabPage with the entry "zone" appears.

Its seems that EditMOM3 doesn't get any informations about the attributes of cei:figure from the xsd. 

Testet directly on the live-server as well

**Comment by StephanMa** [comment]
Nevermind... 
Charter was a Version of an existing Charter. So thats why cei:graphic wasn't shown at all

**Comment by GVogeler** [comment]
We can learn from that, that some indication about this method should be displayed to the user, couldn't we?
