### ISSUE TITLE
Link from Annotation Overview to Edit Charter is broken

### ISSUE THREAD

**Issue by StephanMa** [icaruseu/mom-ca#405]
Currently it is not possible to enter EditMOM3 from the Annotation-Overview. The Link to the Editor isn't set correctly

Module 
http://monasterium.net/mom/user-image-collections

Currently:
http://localhost:8181/mom/charter/[GUID Charter]/edit

Has to be:
http://localhost:8181/mom/[GUID Collection]/[GUID Charter]/edit

**Comment by GVogeler** [comment]
solved with #407
