### ISSUE TITLE
Hinweis auf leere Zeilen beim Excel Import

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#41]

**Comment by icarus-eu** [comment]
I just tried this for some fonds that just came along to import but it seems not to work for all Excel files.
The document below has 6 charters but the import tool still reports 52 lines. Other files work as expected, the tool displays a list of the empty lines.

----

Example:
[Excel document](http://home.icar-us.eu/documents/documents/2015/03/mom-ca-import-doc-with-empty-rows.xls)

**Comment by yngwi** [comment]
I just tried this for some fonds that just came along to import but it seems not to work for all Excel files.
The document below has 6 charters but the import tool still reports 52 lines. Other files work as expected, the tool displays a list of the empty lines (see attached screenshot).

----

Example:
[Excel document](http://home.icar-us.eu/documents/documents/2015/03/mom-ca-import-doc-with-empty-rows.xls)
![screenshot_empty_rows](https://cloud.githubusercontent.com/assets/963440/6917801/71026638-d7a8-11e4-81af-300fa6917044.PNG)

**Comment by strec** [comment]
The reason is that line 47 exists, but it emtpy. Thus excel:sheetinfo returns

```<excel:sheetinfo xmlns:excel="http://exist-db.org/xquery/excel" name="metadata" num="1"><excel:firstrownum num="1"/><excel:lastrownum num="47"/></excel:sheetinfo>```

On this basis, the rows are called. Iterating from firstrownum to lastrownum. Then rows 1-7 return a rowinfo of something similar to this (here it is row 7):

```<excel:rowinfo xmlns:excel="http://exist-db.org/xquery/excel" num="7"><excel:sheet name="metadata" num="7"/><excel:firstcellnum num="1"/><excel:lastcellnum num="20"/></excel:rowinfo>```

Starting with line 8 excel:rowinfo return errors:

```<excel:error xmlns:excel="http://exist-db.org/xquery/excel">Row number '8' does not exist.</excel:error>```

Then line 47 returns a rowinfo of:

```<excel:rowinfo xmlns:excel="http://exist-db.org/xquery/excel" num="47"><excel:sheet name="metadata" num="47"/><excel:firstcellnum num="0"/><excel:lastcellnum num="-1"/></excel:rowinfo>```

If one opens the excel-sheet, selects line 47 and removes it, everything works fine.

**Comment by GVogeler** [comment]
As for the standard user the empty row 47 isn't "visible" we should think about solutions to handle cases like this one.
