### ISSUE TITLE
Dateinamenkontrolle beim XML Import

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#42]

**Comment by strec** [comment]
Kontrolle nach welchen Kriterien?

**Comment by GVogeler** [comment]
Problembeschreibung Karl Heinz: "Konkret heißt das, dass sobald ein Space oder ein Basisstrich im Namen war oder der Name etwas länger war, das Uploadtool die Datei als ungültig qualifiziert hat. Das hat soweit geführt, dass ich alle Quelldateien für die Dauer des Importvorgangs durch die Bank in "a" umbenannt habe. Das hat dann geklappt. Das Problem ist aber wieder eine gute Zeit her. Keine Ahnung, ob es nach wie vor besteht."

**Comment by StephanMa** [comment]
Filenames shouldnt include whitespaces and special characters...
Closed until further notice
