### ISSUE TITLE
EditMOM3 cannot display documents with ampersand in attributes

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#427]
EditMOM3 doesn't display a document, in which &amp; is used in an attribute (e.g. `<cei:ref target="http://.../?param1=1&amp;param2=2">...</cei:ref>`. Storing the `&` URL-encoded as `%26` creates non functional links in single charter view (`cei2html.xsl`).
cfr. #353

**Comment by GVogeler** [comment]
created by an error calling jssaxparser:
```
TypeError: 'prototype' property of InternalEntityNotFoundException is not an object
SAXScanner.prototype.scanAttValue()
javascript:184
SAXScanner.prototype.scanAttribute()
javascript:184
SAXScanner.prototype.scanAttributes()
javascript:184
SAXScanner.prototype.scanElement()
javascript:184
SAXScanner.prototype.scanMarkup()
javascript:184
SAXScanner.prototype.next()
javascript:184
SAXScanner.prototype.continueParsing()
javascript:184
SAXScanner.prototype.parse()
javascript:184
SAXParser.prototype.parseString()
javascript:184
SAX.prototype.parse()
javascript:184
XML.getDescendantElements()
javascript:184
Step.prototype.evaluate()
javascript:184
LocationPath.prototype.evaluate()
javascript:184
XPath.prototype.query()
javascript:184
._create()
javascript:237
$.widget/</prototype[prop]</<()
javascript:52
$.Widget.prototype._createWidget()
javascript:52
$.widget/$[namespace][name]()
javascript:52
$.widget.bridge/$.fn[name]/<()
javascript:52
.each()
javascript:14
jQuery.prototype.each()
javascript:14
$.widget.bridge/$.fn[name]()
javascript:52
createControl()
javascript:269
initControls/<()
javascript:269
.each()
javascript:14
jQuery.prototype.each()
javascript:14
initControls()
javascript:269
$.fn.xrx/<()
javascript:269
.each()
javascript:14
jQuery.prototype.each()
javascript:14
$.fn.xrx()
javascript:269
._create()
javascript:286
$.widget/</prototype[prop]</<()
javascript:52
$.Widget.prototype._createWidget()
javascript:52
$.widget/$[namespace][name]()
javascript:52
$.widget.bridge/$.fn[name]/<()
javascript:52
.each()
javascript:14
jQuery.prototype.each()
javascript:14
$.widget.bridge/$.fn[name]()
javascript:52
<anonym>
edit:20
jQuery.Callbacks/fire()
javascript:14
jQuery.Callbacks/self.fireWith()
javascript:14
.ready()
javascript:14
DOMContentLoaded()
javascript:14
```

**Comment by maburg** [comment]
The problem with the amp; in the attribute does exist because of xquery serialize function - which produces &amp;amp; - this then is not recognized as entity by the saxparser. So the charter instance string has to be partly de-serialized again before further processing. Integrated in widget: mycollection-charter-edit.

**Comment by GVogeler** [comment]
solved by #502

**Comment by GVogeler** [comment]
All documents from http://monasterium.net/mom/ES-AHN/SantaMariadeArmenteira/fond (e.g. http://monasterium.net/mom/ES-AHN/SantaMariadeArmenteira/CLERO-SECULAR_REGULAR%2CCar.1764%2CN.4/charter) seem to have this problem as well.

**Comment by StephanMa** [comment]
Additional Informations (notified by Vera):

In a charter was a placeName reffed like this
`<cei:placeName reg="Silva Plana, locus &gt;">`

After deleting the ">", the charter could be edited again. It looks like that the character "&" isn't allowed at any time.

**Comment by GVogeler** [comment]
additional example: http://monasterium.net/mom/IlluminierteUrkunden/1334-06-24_Klagenfurt/edit
