### ISSUE TITLE
Einbindung von EditMOM 3 als Standardeditor von MOM-CA

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#43]
Gründe: 
- VdUEdit ist zu ressourcenhungrig weil er bei jedem Tastendruck auf den Server zugreift. 
- EditMOM3 enthält Bildwerkzeuge.

Voraussetzungen für den Austausch sind
#226 (erl.)
#216
#217
#445

**Comment by GVogeler** [comment]
see #226 , #217 , #239 , #216 , #220, #130 , #275, #35 
cfr. https://github.com/icaruseu/mom-ca/wiki/Code-structure-of-the-editor

**Comment by StephanMa** [comment]
Der ehemalige XML-Editor kann nun durch EditMOM3 ersetzt werden.
Die Issues #226 und #296 wurden im selben Zug mit bearbeitet.

**Comment by GVogeler** [comment]
Some reports on VdUEdit (Horst Enzensberger 2015-09-28)

"Nach wie vor unerklärlich ist mir, warum zwischen CEI-Tags beim Bearbeiten bisweilen nichts zu sehen ist, aber in der Standardansicht bisweilen doch etwas angezeigt wird. Für die erwünschte Tiefenerschließung des Materials ist das genausowenig hilfreich wie das häufige Versagen der CEI-Tags in den Menues: man markiert die Stelle, wenn man aber den gewünschten Knopf betätigt, geschieht nichts. Oder es verschwindet der eigentlich zu markierende Text völlig vom Bildschirm oder es erscheint ein indefined."
=> VdUEdit creates the whole XML-editing interface on the fly, so with each key pressed the textarea is rebuild.

"Wenig sinnvoll ist auch, daß in das Fußnotenfeld nichts eingesetzt werden kann, obwohl da oft auf vorhandene Angaben anderswo mit c&p zurückgreifen könnte – mom-ca sollte ja auch die Arbeitsökonomie der Bearbeiter in Rechnung stellen. Ich habe sowieso den Eindruck, daß solche Eingaben teilweise wie von einem Zufallsgenerator gesteuert verweigert werden."
=> VdUEdit allows Cut&Paste only over a intermediary window to avoid clipboard-HTML

**Comment by StephanMa** [comment]
Zurückgestellt bis Eingewöhnung von VdUEdit auf EditMOM3 erfolgt ist.

**Comment by GVogeler** [comment]
Aktueller Status: EditMOM3-beta ist überall referenziert

**Comment by GVogeler** [comment]
see #684

**Comment by StephanMa** [comment]
Ich denke, wir können das Issue schließen?

**Comment by StephanMa** [comment]
Closing issue. EditMOM3 is current editor
