### ISSUE TITLE
Collection "MeklenUrk" - Quality of Data

### ISSUE THREAD

**Issue by StephanMa** [icaruseu/mom-ca#433]
The charters 

`/db/mom-data/metadata.charter.public/MeklenUrk/e2827776-12e7-4f64-8ee0-7925cf0b0a82.cei.xml` (value = " ")
and
`/db/mom-data/metadata.charter.public/MeklenUrk/cddf3189-271f-4a3f-aa55-252e084e4a53.cei.xml`
(value = "1241/01/18")
had alphanumeric values in `cei:date/@value`. Displaying any charter of this collection wasn't possible until the data was corrected.

Data was corrected on dev- and on the live-server.

**Comment by GVogeler** [comment]
see #4 as well
