### ISSUE TITLE
Augias image viewer does not show images

### ISSUE THREAD

**Issue by StephanMa** [icaruseu/mom-ca#435]
Currently it isn't possible to use the Augias Imageviewer if the collection isn't published yet.
We should try to enable this, too.
Maybe they have to be changes inside the swf-file which can be a problem.

Need to be verified...

**Comment by GVogeler** [comment]
The problem seems to be related to the server on which the image is hosted: The charter http://monasterium.net/mom/SSRQ_AR_AI_1_Nr_1/SSRQ_Appenzell_1/charter from a public collection does not work as well: http://monasterium.net/augias/viewer.xql?lang=deu&imagedata=/mom/service/augiasviewer&collection-id=SSRQ_AR_AI_1_Nr_1&charter-id=SSRQ_Appenzell_1
probably because the images are not stored on a monasterium.net server.

**Comment by GVogeler** [comment]
Fundamental question: Should we continue the support for the augias-image-viewer at all, as augias image viewer is developed in flash, which is increasingly less well supported by browsers?
Augias image viewer adds the following features to MOM-CA. change-contrast and rotate. Maybe we can achieve that with javascript based image manipulation libraries like openseadragon (https://openseadragon.github.io/)?

**Comment by StephanMa** [comment]
I would definitely switch to a non-flash-tool: openseadragon is definitely worth it. In addition with a plugin, it supports annotations as well. 
I would suggest to replace the image viewer with a JS-based solution

As further comment to my statement above:
If I try to view the image from the origin source, it works well. But when I try to view the same charter just inside a non-published collection, it does not work. Maybe there are more then one error here. In the viewer there aren't any metadata displayed on the right upper corner as well.

**Comment by GVogeler** [comment]
Additional observation: http://monasterium.net/augias/viewer.xql?lang=eng&imagedata=/mom/service/augiasviewer&archive-id=DE-UBHD&fond-id=HeidUrk&charter-id=Heidelberger_Urkunde_325 works well: image (http://digi.ub.uni-heidelberg.de/diglitData/image/heidurk325/4/1_vorderseite.jpg) from external server, public collection.

**Comment by GVogeler** [comment]
@StephanMa yes currently I would assume that it is a problem of the metadata related to the error reported in #436.

**Comment by GVogeler** [comment]
openseadragon does not support contrast/brightness etc. yet, but suggests using CSS3: https://github.com/openseadragon/openseadragon/issues/475

**Comment by GVogeler** [comment]
As Flash is supported be almost no major browser anymore out of the box, this issue can be closed.
