### ISSUE TITLE
EditMOM3 Date entry

### ISSUE THREAD

**Issue by StephanMa** [icaruseu/mom-ca#437]
currently EditMOM3 doesn't allow a datevalue below the year 1000.
e.g. the entry 09250215 isn't valid (validation report).

In connection with #434 it has to be fixed asap.

**Comment by StephanMa** [comment]
As additional information:
9250215 seems to be valid without the leading zero.

Bug or just "unclean" handling?

**Comment by GVogeler** [comment]
I would say "clean handling" as `@value`/`@to` with the second solution can be handled as numerical data (and is handled in this way in the index, I think). Add datatype "integer" to element definition in schema?

**Comment by GVogeler** [comment]
and check if dates with leading 0 exist in data for improvement of data quality?

**Comment by StephanMa** [comment]
In the documentation there is also mentioned that the date has to be entered like "yyyymmdd".
Thats why i became confused.

The leading zero should not lead to any data-error inside mom-ca. Its just a question of entering data / validation.

**Comment by GVogeler** [comment]
OK, then we have to change the documentation/help information.

**Comment by StephanMa** [comment]
As additional reference: 
http://dev.monasterium.net/mom/mom/editmom-documentation#/text/body/chDesc/issued/date

"Bsp.: 1230 Mai wird zu 1230-05-99, 843 wird zur 843-99-99" 

We should rework the documention very well, i guess... because this example above is obviously not numeric...

**Comment by GVogeler** [comment]
OK then it's https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/EditMOM/template/EditMOM.template.xml
