### ISSUE TITLE
reset password shows no reaction on frontend

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#439]
After filling in the form in http://monasterium.net/mom/request-password the user should get a response "An e-mail with further instructions on how to reset your password has been send to your address."

**Comment by StephanMa** [comment]
Script has a feedback-function to give a response to the user.
Unfortunately it isn't displayed at all.

See: https://github.com/icaruseu/mom-ca/blob/6ca05211e11eeaf112296cb81804d7b9194e6fa9/my/XRX/src/core/app/user/widget/request-password.widget.xml#L70

The response was generated within https://github.com/icaruseu/mom-ca/blob/6ca05211e11eeaf112296cb81804d7b9194e6fa9/my/XRX/src/core/app/user/service/request-password.service.xml 

We have to ensure that the feedback is shown within the browser.

**Comment by StephanMa** [comment]
It seems that the widget isn't able to handle the response of the service.
When you change the type of submission from `replace=instance` to `replace=all`, you can see that the response from the service is totally correct. But the widget does not take any notice from the response and does not use the instance-information for the output.

Maybe related to: #302  and i am pretty sure many more...
