### ISSUE TITLE
bookmark of some charters leads to error in bookmarks overview

### ISSUE THREAD

**Issue by JBigalke** [icaruseu/mom-ca#451]
Some Charters with a specific kind of atom:id lead to an error in the bookmarks overview. 
Error: 
 The actual cardinality for parameter 1 does not match the cardinality declared in the function's signature: metadata:objectid($atomid as xs:string) xs:string. Expected cardinality: exactly one, got 0. [at line 161, column 26, source: String]
In function: metadata:objectid(xs:string) [394:831:/db/XRX.live/mom/app/metadata/metadata.xqm]

All Charters with this kind of atom:id causes the problem: 
tag:www.monasterium.net,2011:/charter/7b78733a-44ef-4bde-b98d-53e49c8b9619/3bd98b80-25dc-4a51-bb43-28586cb0d8de

**Comment by JBigalke** [comment]
metadata:base-collection-path() creates a wrong path to the charter

www.monasterium.net,2011:/charter/7b78733a-44ef-4bde-b98d-53e49c8b9619/3bd98b80-25dc-4a51-bb43-28586cb0d8de 
leads to the charter-path: /db/mom-data/metadata.charter.public/**charter/25e2f0b4-20ac-4ee6-822e-bc14da28d226/**

correct path =  /db/mom-data/metadata.charter.public/**25e2f0b4-20ac-4ee6-822e-bc14da28d226/3bd98b80-25dc-4a51-bb43-28586cb0d8de**

**Comment by JBigalke** [comment]
Two Problems:

1. Problem: 
There are two Paths for published Collections. 
first path is: 
 /db/mom-data/metadata.collection.public 
second path is:
/db/mom.data/metadata.**my**collection.public
Bookmark.widget.xml searchs the collection only in the first path.

2. Problem:
atom:id for collection in path 1 is:   tag:www.monasterium.net,2011:/collection/...
in path 2 : tag:www.monasterium.net,2011:/**my**collection/...

Bookmarks.widget.xml only knew the first kind of atom:id

**Comment by StephanMa** [comment]
Suggestion:
Merge collections and build `atom:id` the same way. An identification of a user-Collection is still possible with the `atom:email` tag inside

**Comment by GVogeler** [comment]
@StephanMa: From the data structure I don't see any reason to keep the distinction. But we would have to modify the publication process and maybe the management of user collections in the frontend. `mycollection` occurs at least at 31 places in the code: https://github.com/icaruseu/mom-ca/search?utf8=%E2%9C%93&q=mycollection

**Comment by GVogeler** [comment]
see #469 and #476

**Comment by StephanMa** [comment]
It means that the charters couldn’t be found in the context. The charters are deleted or moved else where. 
Maybe the script isn’t able to detect the mycollection?

**Comment by GVogeler** [comment]
solve with #761
