### ISSUE TITLE
Allow preselection of collections/fonds in search2

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#458]
Search results in search2 can be drilled down to fonds and collections by the GET paramater `context` (e.g. http://www.monasterium.net/mom/search2?q=koloriert&option=and&img=&annotations=&sort=date&categories=cei%3AwitnessOrig%2Ccei%3AphysicalDesc%2Ccei%3Aabstract&context=AT-StiASP%3BUrkunden%2CIlluminierteUrkunden).
search2 could contain a html-select-box listing all archival fonds and collections.
The select-box could be preselected by a GET-parameter `context` for mom/search2 to allow links between starting pages of fonds and collections to dedicated search as it is currently the case for archives and fonds (e.g. http://dev.monasterium.net/mom/AT-StiAStP/BlUKBebenhausen/fond)

**Comment by GVogeler** [comment]
to be part of #177?

**Comment by StephanMa** [comment]
Currenty, search2 gets the parameter as session-variable.
see: https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/search/widget/search2.widget.xml#L57

ToDo: Rework the widget to get a session-value OR a get-value, depending on whats available.

**Comment by GVogeler** [comment]
solved with #767
