### ISSUE TITLE
modifiy authentication in a way, that archivists (community members) can publish charters from their archive

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#492]
Currently community members (https://github.com/icaruseu/mom-ca/wiki/authentication#community) can only change description of archive and fonds, create and delete fonds and import charters. They should have the right to publish charters from their archives as well (https://github.com/icaruseu/mom-ca/tree/master/my/XRX/src/core/app/auth)

**Comment by StephanMa** [comment]
To be clear:
a Community-member of an archive should be able to publish charters even when she/he is >not< the dedicated moderator of the submitting user?

**Comment by GVogeler** [comment]
If the charter is part of her/his archive, yes.

**Comment by StephanMa** [comment]
To do:
- check, if user is a community-member; if so, extract archive
- get all charters from the user-collection which have `xrx:freigabe=yes`
- extract all ids and especially the corresponding archive
- check if the archives match... if so, take charter for the release-process

Files:
- my/XRX/src/mom/app/publication/widget/charters-to-publish.widget.xml
- publication.xqm

on it

**Comment by StephanMa** [comment]
done... will be pushed next week due of organisatorical issues

**Comment by StephanMa** [comment]
pushed... will be tested on next merge (Thursday?)

**Comment by GVogeler** [comment]
closed with #517, follow up #526 and #527
