### ISSUE TITLE
Doppelte Anmeldung beim Import vermeiden

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#5]
Die Importumgebung auf uni-koeln.de läuft unter einer anderen URL

**Comment by strec** [comment]
Hat sich dieses Issue mit dem Umzug erledigt?

**Comment by GVogeler** [comment]
Existiert immer noch: http://ftp.dioezesanarchiv.acw.at:8181/mom/CAO/cei-import

**Comment by strec** [comment]
Bei welchem Benutzer mit welchen zugewiesenen Rollen tritt das auf? Am besten mal kurz den Workflow skizzieren...
Konnte es bisher nicht reproduzieren. Nutzer, die Metadata-Manager sind, müssen sich bei mir lokal nicht erneut einloggen.

**Comment by GVogeler** [comment]
Angemeldet g.vogeler@lrz.uni-muenchen.de (Rollen: moderator, translator, metadata-manager, html-author) verweisen unter http://monasterium.net/mom/...ID.../import-charters alle Import-Links auf http://ftp.dioezesanarchiv.acw.at:8181. 
z.B. http://ftp.dioezesanarchiv.acw.at:8181/mom/DE-UBHD/HeidUrk/excel-import, http://monasterium.net/mom/AFM/import-charters, http://monasterium.net/mom/GVtestzwo/import-charters
Workflow: Zeige Dir eine Samlung/einen Bestand an, wähle "Urkunden importieren", führt zu http://monasterium.net/mom/...ID.../import-charters, wo dann bei mir alle Import-Links wie oben sind.

**Comment by yngwi** [comment]
1. Besuch von monasterium.net
2. Auswählen eines Archivs/Bestands
3. Anmeldung mit meinem Benutzer, mit den Rollen `moderator metadata-manager translator user-administrator html-author `
4. Klick auf `Import Charters`
5. Klick auf (z.B.) `Excel import`
6. Automatischer Redirect auf `ftp.dioezesanarchiv.acw.at:8181` mit der Notwendigkeit einzuloggen.
7. Abwicklung des Importvorgangs

----

Bei mir ist es immer so, dass alle Bestandsarbeiten erst nach einem Redirect auf `ftp.dioezesanarchiv.acw.at`, das ist direkt der Apache auf dem Server hier, erfolgen.

**Comment by StephanMa** [comment]
Ich habe mich auf monasterium.net registriert. Aber Daniel hat das Problem ja bereit bestätigt.

**Comment by strec** [comment]
Mein Benutzer-Account bei monasterium.net hat aktuell die Rollen:
Das Problem liegt vermutlich nicht direkt im Bereich des mom-ca Quellcodes. Man müsste mal in den Dateien auf dem Server stöbern...
