### ISSUE TITLE
search with apostroph returns XRX:error

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#501]
search for `Sant'Agata` in search2 (http://monasterium.net/mom/search2?q=Sant%27Agata&option=and&img=&annotations=&sort=date&categories=&context=) and search( http://monasterium.net/mom/search?q=Sant%27Agata&sort=date&arch=) returns an XRX-Error:

```
Error while evaluating expression: let $context := collection("/db/mom-data/metadata.charter.public") for $charter in $context//cei:text[ft:query(.,'Sant"Agata',$search:options)] order by ($charter//cei:date/@value, $charter//cei:dateRange/@from, $charter//cei:dateRange/@to)[1] ascending  return $charter. Error while querying full text index: Cannot parse 'Sant"Agata': Lexical error at line 1, column 11.  Encountered: <EOF> after : "\"Agata" [at line 161, column 26]
In function:
    search:eval(item()*) [213:34:/db/XRX.live/mom/app/search/search.xqm]
    local:eval(element()) [292:30:/db/XRX.live/mom/app/xrx/main.xql]
    local:mode-mainwidget() [427:13:/db/XRX.live/mom/app/xrx/main.xql]
    local:main() [444:1:/db/XRX.live/mom/app/xrx/main.xql]
```

**Comment by StephanMa** [comment]
The error occurs because the single apostrophe is "destroying" the syntax. 
A dirty hack is to escape such a character into a "?". 

i.e.: `Sant'Agata -> Sant?Agata`

It totally works when entering the string above in the Searchfield.

**Comment by GVogeler** [comment]
Great, it even works when apostrophe is on the second position: `L'Aqulia => L?Aquila`! So it's an acceptable work-around, if we don't find the escaping mechanism we could apply to the apostrophe. Do we already know where in the query process the syntax is "destroyed"?

**Comment by StephanMa** [comment]
To my mint... it should be

https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/search/search.xqm#L197

i will try to fix it at my local maschine and submit a pr soon

**Comment by GVogeler** [comment]
OK, we have a double quotation in `'", $search:q, "'`. Can't we use the double quote in the outside, and escape the double quote in inside? Or use a function to stringify the phrase? (Btw Lucene escaping: http://lucene.apache.org/core/2_9_4/queryparsersyntax.html#Escaping%20Special%20Characters. Anywhere a documentation of escaping in `ft:query()`?)

**Comment by StephanMa** [comment]
it seems that 
https://github.com/icaruseu/mom-ca/blob/57134ff12dc83234e9c32e62889378d6a364381e/my/XRX/src/mom/app/search/search.xqm#L42

is making the Problems.... replacing the `" with ?` will lead to our workaround.

**Comment by StephanMa** [comment]
can be closed?

**Comment by GVogeler** [comment]
remaining issues moved to #518
