### ISSUE TITLE
charters with non-integer values in `cei:date/@value`

### ISSUE THREAD

**Issue by StephanMa** [icaruseu/mom-ca#510]
After doing some reindexing of my local exist-db, I discovered that there are around 30 charters (maybe more because of testdata), which haven't the expected xs:integer-value in @value.

Some of the values are:
"" (empty)
0,5 (which is a float)
0.5 (which is a float)

Unfortunately no atom:id was given but it should be easy to adress them.

**Comment by GVogeler** [comment]
`cei:dateRange[@to='' or @to='0,5' or @to='0.5']` returns:
 tag:www.monasterium.net,2011:/charter/HU-MFL/Toeroekiratok/15619999_115
    tag:www.monasterium.net,2011:/charter/HU-MFL/Toeroekiratok/15689999_77
    tag:www.monasterium.net,2011:/charter/BISANU/1322xxxx_tpq-Stefan_Decanski
    tag:www.monasterium.net,2011:/charter/BISANU/132405xx_tpq-Stefan_Decanski
    tag:www.monasterium.net,2011:/charter/BISANU/132409xx_tpq-Stefan_Decanski
    tag:www.monasterium.net,2011:/charter/BISANU/137905xx_tpq-Lazar
    tag:www.monasterium.net,2011:/charter/BISANU/13800901_byz-Lazar
    tag:www.monasterium.net,2011:/charter/BISANU/138801xx-Lazar
    tag:www.monasterium.net,2011:/charter/DE-AKR/Urkunden/SpAR_Urk_1999
    tag:www.monasterium.net,2011:/charter/DE-AKR/Urkunden/SpAR_Urk_630
    tag:www.monasterium.net,2011:/charter/DE-AKR/Urkunden/SpAR_Urk_64
    tag:www.monasterium.net,2011:/charter/DE-AKR/Urkunden/SpAR_Urk_74
    tag:www.monasterium.net,2011:/charter/DE-AKR/Urkunden/SpAR_Urk_93
    tag:www.monasterium.net,2011:/charter/DE-AKR/Urkunden/ca12819999
    tag:www.monasterium.net,2011:/charter/DE-AKR/Urkunden/SpAR_Urk_119a
    tag:www.monasterium.net,2011:/charter/DE-AKR/Urkunden/SpAR_Urk_136
    tag:www.monasterium.net,2011:/charter/DE-AKR/Urkunden/SpAR_Urk_1477

**Comment by GVogeler** [comment]
```for $u in collection('/db/mom-data/metadata.charter.public/')//cei:date[string(xs:integer(@value)) != string(@value)]
return $u```
returns only `@value` with leading `0`.

**Comment by GVogeler** [comment]
`cei:dateRange[@from='' or @from='0,5' or @from='0.5']` returns an empty sequence.

**Comment by GVogeler** [comment]
@maburg reports: 

> im Fall von Vera steht der Text im cei:issued: das ist nur dann möglich, wenn ,wie sie das macht, einen Elementknoten mit Text kopiert, dann wird zwar geschrieben - 'invalid selection', aber ohne Folgen.

**Comment by StephanMa** [comment]
Should be fixed until further notice
