### ISSUE TITLE
i18n system can create error when updating i18n database via "update"

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#519]
When clicking on `Update Now` in http://monasterium.net/mom/translate?lang=deu&catalog=all&only-untranslated=true&key=&q=&id=tag:www.monasterium.net,2011:/mom/widget/charter MOM-CA returns a `Error while updating catalogues` message.

The error is created in mom-ca/my/XRX/src/core/app/i18n/widget/translate.widget.xml when triggering the [service `update-i18n-catalog`](https://github.com/icaruseu/mom-ca/blob/57134ff12dc83234e9c32e62889378d6a364381e/my/XRX/src/mom/app/i18n/service/update-i18n-catalog.service.xml)  (which is inherited from [core](https://github.com/icaruseu/mom-ca/blob/57134ff12dc83234e9c32e62889378d6a364381e/my/XRX/src/core/app/i18n/service/update-i18n-catalog.service.xml) and uses the function [`catalog:update()` from catalog.xqm](https://github.com/icaruseu/mom-ca/blob/57134ff12dc83234e9c32e62889378d6a364381e/my/XRX/src/core/app/i18n/catalog.xqm#L38) ) by executing the xforms submission in https://github.com/icaruseu/mom-ca/blob/57134ff12dc83234e9c32e62889378d6a364381e/my/XRX/src/core/app/i18n/widget/translate.widget.xml#L367

**Comment by GVogeler** [comment]
Same behaviour in http://monasterium.net/mom/translate .

**Comment by GVogeler** [comment]
Test if the use of whitespace in the `xrx:key` in https://github.com/icaruseu/mom-ca/blob/bd7c21def18c9bd56c9fdd3b56c073a34e313fcd/my/XRX/src/mom/app/charter/widget/charter.widget.xml#L980 could be the reason. It's the only `xrx:key` in mom-ca-Code which uses whitespace and it has been added recently (66607546cd572f3a2d013c122f649d86224ae8ef).

**Comment by StephanMa** [comment]
This point with the whitespace in the xrx.key was pointed out by me inside of the pr. But it has to be analyzed...

**Comment by StephanMa** [comment]
I can confirm that this error just occurs when `xrx:key` is including some string with a whitespace.
