### ISSUE TITLE
Add link to "charters-to-publish" for archivists

### ISSUE THREAD

**Issue by yngwi** [icaruseu/mom-ca#526]
Since #492 , archivists are able to publish edited charters of 'their' archive. They can do this from `http://monasterium.net/mom/charters-to-publish`. Currently, they can access this page but there is no link displayed to reach this page in `MyArchive` because they need to be at least of the role `moderator` to access this page from MyArchive. This needs to be changed.

**Comment by StephanMa** [comment]
Possible Solutions:

- While adding an archivist, it will be automatically added a moderator tag for the user.

- Add a new role to the System (archivist) which is queryable for the system

**Comment by GVogeler** [comment]
I would prefer the addition of a new role, as members of the group `moderator` can be selected by users as moderators.

**Comment by StephanMa** [comment]
- Added another `<xrx:role>` "achivist" which allows the archivist to handle "charters to publish" into role.app.xml for their archive
- Added `<xrx:auth>`-method for role `archivist` in `desktop-left-menu.widget.xml`
