### ISSUE TITLE
`cei:abstracts` displays an unexpected "x" at the end.

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#534]
e.g. in http://www.monasterium.net/mom/DE-GAUnivGoet/AppDipl/App_dipl_2/charter or http://www.monasterium.net/mom/DE-GAUnivGoet/AppDiplBrondolo/App_dipl_Brondolo_1/charter the abstract area of the charter display shows an "x" which which does not have any meaning. As it isn't part of the XML source, it probably is introduced by code.

**Comment by GVogeler** [comment]
possible candidate for the cause of this problem is:

https://github.com/icaruseu/mom-ca/blob/bd7c21def18c9bd56c9fdd3b56c073a34e313fcd/my/XRX/src/mom/app/charter/xsl/cei2html.xsl#L251

(other place where `cei2html.xsl` introduces a single `x` are:

https://github.com/icaruseu/mom-ca/blob/bd7c21def18c9bd56c9fdd3b56c073a34e313fcd/my/XRX/src/mom/app/charter/xsl/cei2html.xsl#L370

https://github.com/icaruseu/mom-ca/blob/bd7c21def18c9bd56c9fdd3b56c073a34e313fcd/my/XRX/src/mom/app/charter/xsl/cei2html.xsl#L1689

but they aren't related to `cei:abstract`.)

**Comment by StephanMa** [comment]
https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/charter/xsl/cei2html.xsl#L251 is the point.

I don't even know why there should be an "x" anyway. Can be easily disabled

**Comment by GVogeler** [comment]
I personally see no reason, why it's there. Maybe @maburg (with the most experience in cei2html.xsl probably) knows a reason?
