### ISSUE TITLE
Charter-view does not display `cei:witListPar/cei:witness` when there is a `cei:witnessOrig`

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#535]
e.g. http://www.monasterium.net/mom/DE-GAUnivGoet/AppDipl/App_dipl_397%28II%29/charter

Charters with `cei:witListPar/cei:witness` and `cei:witnessOrig` occur 14830 times in the whole data set.

Maybe a problem in the template defined in https://github.com/icaruseu/mom-ca/blob/bd7c21def18c9bd56c9fdd3b56c073a34e313fcd/my/XRX/src/mom/app/charter/xsl/cei2html.xsl#L129 ?

**Comment by GVogeler** [comment]
I would check, if https://github.com/icaruseu/mom-ca/blob/bd7c21def18c9bd56c9fdd3b56c073a34e313fcd/my/XRX/src/mom/app/charter/xsl/cei2html.xsl#L183 causes the problem as the display of `cei:witnessOrig` and `cei:witness` is not an alternative (`xsl:choose`). So maybe better wrap both cases into a `cei:if` instead?

**Comment by StephanMa** [comment]
Yes you are totally right.
But i am not sure if this is a bug or an enhancement.

Should both be displayed? Then this has to be moved from choose to if.

**Comment by GVogeler** [comment]
Both should be displayed (and once were displayed if I remember right), because:
* Archives provide this information (it occurs in 14.830 cases ...) and thus expect, that the information is visible
* Diplomatists documents this (sometimes)

**Comment by GVogeler** [comment]
cfr #172

**Comment by GVogeler** [comment]
closed with #649

**Comment by GVogeler** [comment]
http://www.monasterium.net/mom/DE-GAUnivGoet/AppDipl/App_dipl_397%28II%29/charter still only shows the information from `cei:witnessOrig`:
```
<cei:witnessOrig><cei:figure><cei:graphic url="Goettingen_App_Dipl_397_15850905_r.JPG"/></cei:figure><cei:figure><cei:graphic url="Goettingen_App_Dipl_397_15850905_v.JPG"/></cei:figure><cei:archIdentifier><cei:arch>Göttingen, Diplomatischer Apparat</cei:arch><cei:archFond>App. dipl.</cei:archFond><cei:idno>397</cei:idno></cei:archIdentifier><cei:traditioForm>ins.</cei:traditioForm></cei:witnessOrig><cei:witListPar><cei:witness><cei:traditioForm>cop. </cei:traditioForm>App. dipl. 51</cei:witness></cei:witListPar>
```
results in:

![screenshot-2017-12-2 charter de-gaunivgoet appdipl app_dipl_397 28ii 29 - monasterium net](https://user-images.githubusercontent.com/324006/33518234-ea681342-d791-11e7-883a-ce07e6dffb2b.png)

**Comment by GVogeler** [comment]
It seems that https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/charter/xsl/cei2html.xsl#L200 does not test wide enough. Changing it to `$ordered-witListPar/cei:witness//text() != ''"` could help with that.
