### ISSUE TITLE
`atom:author` and user-id in `xrx:user` collections are not synchron

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#554]
```
xquery version "3.0";
declare namespace atom = "http://www.w3.org/2005/Atom";
declare namespace cei = "http://www.monasterium.net/NS/cei";

for $u in count(collection('/db/mom-data/xrx.user/')//atom:entry[contains(atom:id, 'charter')][
    replace(substring-before(substring-after(base-uri(.), 'xrx.user/'), '/metadata.charter'), '%40', '@') != atom:author/atom:email/string() 
    ])
return $u
```

return 110 cases, in which the user coded in the base-uri is not the same as `atom:author/atom:email`.

This creates problems since the introduction of owner rights in shared charters in #552.

**Comment by GVogeler** [comment]
Possible solutions:
1. make data more consistent (change `atom:author/atom:email`) 
or
2. change https://github.com/JBigalke/mom-ca/blob/7e9b04e97c7d6b3d576ace30cbf207684f5b5b81/my/XRX/src/mom/app/collection/widget/my-collection-charter-edit.widget.xml#L67 to test for user encoded in base-uri.

**Comment by GVogeler** [comment]
Many of the cases come from legacy data of charters created directly via eXist. But there are cases, which more probaly result from a charter created in MOM-CA:

`/db/mom-data/xrx.user/martina.buergermeister%40uni-graz.at/metadata.charter/d737b70d-24e3-414a-8cdc-f780608258d2/97abbea9-5e0a-4fcd-8c74-cd35bbc78ff0.charter.xml` with `<atom:email xmlns:atom="http://www.w3.org/2005/Atom">guest</atom:email>`

`/db/mom-data/xrx.user/markus.gneiss%40oeaw.ac.at/metadata.charter/4a260b05-e94e-4f58-af5a-62c0886d0a56/0a7b31c5-6010-4cda-aedf-9635f02ff198.charter.xml` with `<atom:email xmlns:atom="http://www.w3.org/2005/Atom">guest</atom:email>`

`"/db/mom-data/xrx.user/stephan.makowski%40uni-koeln.de/metadata.charter/cbeb4c09-5964-4d99-bd04-f526ef72a58c/d8a4ab66-f52b-41de-91fa-b4177af12e5d.charter.xml` with `<atom:email xmlns:atom="http://www.w3.org/2005/Atom">admin</atom:email>`

**Comment by GVogeler** [comment]
https://github.com/icaruseu/mom-ca/blob/57134ff12dc83234e9c32e62889378d6a364381e/my/XRX/src/mom/app/collection/mycollection.xqm#L80 uses `util:collection-name()` to identify owner.

**Comment by StephanMa** [comment]
AS you had already said, i would like to clean up the data. Identify the owner by collection is not a good choice.

The only think i would like to investigate are the charters which were modified by the `guest` -account user.

**Comment by GVogeler** [comment]
Current cases solved by solution 1

**Comment by GVogeler** [comment]
Follow-up #556
