### ISSUE TITLE
EditMOM3 seems to be able to add `atom:author/atom:email`different from logged-in user/original owner of a document

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#556]
/db/mom-data/xrx.user/martina.buergermeister%40uni-graz.at/metadata.charter/d737b70d-24e3-414a-8cdc-f780608258d2/97abbea9-5e0a-4fcd-8c74-cd35bbc78ff0.charter.xml with <atom:email xmlns:atom="http://www.w3.org/2005/Atom">guest</atom:email>

/db/mom-data/xrx.user/markus.gneiss%40oeaw.ac.at/metadata.charter/4a260b05-e94e-4f58-af5a-62c0886d0a56/0a7b31c5-6010-4cda-aedf-9635f02ff198.charter.xml with <atom:email xmlns:atom="http://www.w3.org/2005/Atom">guest</atom:email>

"/db/mom-data/xrx.user/stephan.makowski%40uni-koeln.de/metadata.charter/cbeb4c09-5964-4d99-bd04-f526ef72a58c/d8a4ab66-f52b-41de-91fa-b4177af12e5d.charter.xml with <atom:email xmlns:atom="http://www.w3.org/2005/Atom">admin</atom:email>

**Comment by StephanMa** [comment]
Bug confirmed

When you are working with EditMOM3 and you have a session timeout, all changes are made with the guest account.

To Do:
In the writting service  has to be checked if the current session is valid. This could be tricky because the session module seems to be buggy; e.g.:
when you make `session:invalidate()` and afterwards a `session:exists()` you return a `true` which is wrong. So we have to think about a doable solution.

**Comment by yngwi** [comment]
Will the proposed update to eXist 2.2 help? Maybe the session module is less buggy?

**Comment by StephanMa** [comment]
Tested on eXist 2.0 & 2.2 unfortunately the same result...

**Comment by StephanMa** [comment]
Workaround:

After logging in into MOM, the individual session contains the xml-db username as attribute. When you have invalidated the session (or session is timed out), the attribute is no longer part of the session, even when the session is still marked as active. So we have to check, is the user inside the session attribute is available. if not, reject changes.

**Comment by StephanMa** [comment]
This will lead us to the question:
The user does not know that a session has become invalide. We have to establish a service that checks periodically if the session is still valid or not. If not, display a red message and, maybe, set all input fields to readonly. @GVogeler @yngwi  suggestions?

**Comment by GVogeler** [comment]
Alternative approach: Keep session active while EditMOM3 is open. This would give the possibility to solve #64 as well. Would need a mechanisms how to handle "implicitly closed" session (i.e. sessions expired during to hibernation mode of OS or other possibilities in which browser looses connection).

**Comment by StephanMa** [comment]
I don't think its that easy, because eXist does not really allow too much of session handling. Maybe we have to login everytime the editor notices that the session has expired. But... i dont know how to grab the current password. So we are not able to do any re-login. 
We have to make any further tests how to handle sessions probably

**Comment by StephanMa** [comment]
Suggestion:
Write a "session-handling"-file inside of a temp Collection. Do an entry everytime the editor is started with some data (atom-id of edited charter, date and timestamp, userid). When editor is closed, we need to remove this lock-entry/lock-file. 
As long as the editor stays open, the entry exists, the changes has to be made with the user from the lockdata. 
Attention: We have to ensure that the file is allways cleared up after the editor is closed. Maybe we should enable a trigger, which deletes every lock-file which was opened 24h ago and is not removed yet.

**Comment by GVogeler** [comment]
Sounds interesting!
Maybe we could add the locking-information to the file itself (`xrx:lock` with information in `xrx:when` and `xrx:by`)? That would avoid an additional database query when the charter is read dir editing or even for listing/display.

**Comment by GVogeler** [comment]
Checking for lost lock-off could even be done, when  the file is requested for opening to edit, e.g. giving the user feedback ("This charter was locked for editing by XY and last changed more than 24 hours ago. It is probable that it's not actively modified anymore. Shall EditMOM remove the lock to allow you  editing?") or even informing the original user via mail.

**Comment by JBigalke** [comment]
In Pull request #571 MomEdit3 reloads when the user is logged out. And so the login form in EditMom3 appears. I think a message isn't needed. 
Case 1: The user logged out by hand in Monasterium and doesn't close the Editor. 
Case 2: The user is inactive for 30 minutes, the session is expired. 
In both cases we can assume that there is no data loss.
Optionally we could add an alert which informs the user about the log out.

**Comment by GVogeler** [comment]
In case of shared documents we have an additional problem:
As it seems the current state of code (before PR #571) writes the user-id/e-mail of the editing user into the XML. When a charter is shared with another user and this user edits the charter, then the e-mail of this "shared" user is saved in the `atom:author`. When the original user wants to edit the charter, the authentication system does not allow accessing it anymore.

**Comment by StephanMa** [comment]
@JBigalke can you please have a look?

**Comment by JBigalke** [comment]
Maybe it is a quick and dirty solution, but I created a function which gets from the collection URI the email.
example:
/db/mom-data/xrx.user/**JBigalke@smail.uni-koeln.de**/metadata.charter/932f3af5-b595-4af4-a8d5-e91cd54abce1/f4ba0877-1af2-40c3-9fc8-3b37c3725a56.charter.xml

when the email is same as the logged in user name it should be an charter in the collection from the user even when the author mail is different.

**Comment by GVogeler** [comment]
That is somehow the original solution by Jochen :-) But if it works, it's fine.

**Comment by GVogeler** [comment]
Obviously the authorisation system needs a major refactoring, which distinguishes clearly between:

* owner of a document
* (owner of a collection as rights can be inherited from this)
* allowed editor (e.g. individually by sharing or by moderation or via collection hierarchy by archivist ('community': https://github.com/icaruseu/mom-ca/wiki/User-roles and https://github.com/icaruseu/mom-ca/wiki/Authentication#community )
* author of last modification

This should allow separating single documents from the eXist-collection structure.

**Comment by JBigalke** [comment]
Maybe we could change the *.charter.share.xml from 
<xrx:share xmlns:xrx="http://www.monasterium.net/NS/xrx">
    <xrx:userid>admin</xrx:userid>
</xrx:share>
to something like:
<xrx:owner>Owneride</xrx:owner
<xrx:share>sharedid</xrx:share>
<xrx:share>-...

but then we need a script to change all *.charter.share.xml

**Comment by GVogeler** [comment]
No we should finally add the `<xrx:userid type="owner">...</xrx:userid>` to all `*.charter.share.xml`

**Comment by icarus-eu** [comment]
Already done after deploying the pull request.

**Comment by GVogeler** [comment]
cool!
