### ISSUE TITLE
Superfluous comma after date for charters with empty cei:issued/cei:placeName

### ISSUE THREAD

**Issue by icarus-eu** [icaruseu/mom-ca#564]
It can happen that `cei:issued` contains an empty `cei:placeName` Element:

CEI:
```xml
<cei:issued
    <cei:placeName/
    <cei:date value="11380430">11380430</cei:date
</cei:issued>
```

Website:
![comma](https://cloud.githubusercontent.com/assets/6792937/23548875/d5d434f2-0009-11e7-8091-7e294c0b6b26.PNG)

**Comment by StephanMa** [comment]
Has to be fixed in https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/charter/xsl/cei2html.xsl
