### ISSUE TITLE
search results were ordered chronologically in earlier MOM-CA but currently aren't

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#577]
Observation by Martin Roland without a precise date of change unfortunately.
Example: http://monasterium.net/mom/search?q=Fleuronn%C3%A9e&option=and&img=&annotations=&sort=date&categories=&context= and http://monasterium.net/mom/search2?q=Fleuronn%C3%A9e&option=and&img=&annotations=&sort=date&categories=&context=:
has years 1288, 1351, 1330, 1295, 1296, 1297, 1360, 1328, 1351, 1299, 1290, 1331, 1374, 1375, 1398, 1335, 1453, 1233, 1343, 1287, 1428, 1288.

**Comment by GVogeler** [comment]
Seems to be sorted chronologically by fonds/collection, should be by whole search result

**Comment by StephanMa** [comment]
I can not reproduce the error.

To clearify: just open the search-url in the browser is not the way how the search is working. It is currently +not+ possible to use the search just with the url paramenters. Thats why the search does not sort the results correctly. 
It works by set the sessions variables. So you have to enter the search string manually or hit the apply button in search2 to get the correct orderstate.

**Comment by GVogeler** [comment]
Unfortunately I can confirm the bug with my machine even when enterig a new search string manually.
go to http://monasterium.net/mom/search
enter "Fleuronn*" into the search control
hit "search"
result puts 1478 März 25 (http://monasterium.net/mom/SchneiderTest/2.48/charter?q=Fleuronn*) before 1351-06-13 (http://monasterium.net/mom/IlluminierteUrkunden/1351-06-13_Bregenz/charter?q=Fleuronn*).

**Comment by GVogeler** [comment]
Another example:
Searching for "Ablassurkunde*" in http://monasterium.net/mom/search gives on page 3 not only a restaten in search order when starting a new archival fonds (St. Gallen, Chartularium Sangallense VIChartularium Sangallense 06 (1327-1347)Schweiz ), but also orders the charters from the collection 'Illuminierte Urkunden' in a non-chronological way.

**Comment by GVogeler** [comment]
Probably the problem lies in
https://github.com/icaruseu/mom-ca/blob/8b8867e93a3f3836d5c42d993b6e59342c232d72/my/XRX/src/mom/app/search/search.xqm#L221
where the order is a list not an "or":
```
for $charter in collection('/db/mom-data/metadata.charter.public/IlluminierteUrkunden')//atom:entry
order by (number($charter//cei:issued/cei:date[1]/@value), number($charter//cei:issued/cei:dateRange[1]/@from), number($charter//cei:issued/cei:dateRange[1]/@to))[1] ascending
return $charter//cei:issued
```
(order clause from current code) returns the fonds a sequence in a non-chronological order, while 
`order by number($charter//cei:issued/(cei:date/@value[.!='']|cei:dateRange/@to))` gives a correct chronological sequence.

**Comment by StephanMa** [comment]
Deployed. Closing
