### ISSUE TITLE
search is performance critical

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#582]
investigate what crashed the search

**Comment by GVogeler** [comment]
e.g. http://monasterium.net/mom/search?q=Friedrich&sort=date&arch=

**Comment by icarus-eu** [comment]
Complex searches: `He*` takes on a 2 Cores, 8GB RAM Virtual Machine 2-3 Minutes and delivers 162129 results without crashing.

**Comment by StephanMa** [comment]
Search does not crash any longer. maybe related to #501 and can be closed?

**Comment by GVogeler** [comment]
currently no crashed reproducable with the example above.
