### ISSUE TITLE
EditMOM3 as alternative editor should be accessible from 'everywhere'

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#583]
from single charter view, from fonds/collection/search hit list

**Comment by StephanMa** [comment]
Some thoughts about the UI?
Currently you need to "save and edit" a charter. Save is still needed. Should the standardeditor be EditMOM3? (Not able to add new fields)
Same at search list : Editing charters from the result seems to be a new feature

**Comment by GVogeler** [comment]
UI: I would suggest to put "save for editing" and then the double solution `Edit charter` and `Edit with EditMOM 3 beta` from /saved-charter (maybe even reuse code as a common widget possible, that changing solution later on might become easier?)

**Comment by GVogeler** [comment]
Search-list: I don't see any reasons why save & edit is possible in /search but not in /search2

**Comment by StephanMa** [comment]
Was deployed. Can be closed?

**Comment by GVogeler** [comment]
close with #604
