### ISSUE TITLE
display thumbnails of images hosted by ICARus

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#594]
most effective solution could be a [IIIF](http://iiif.io/) based image server like https://github.com/loris-imageserver/loris and OpenSeaDragon as image viewport (see #494 ).

**Comment by GVogeler** [comment]
iiif solution would allow:
* deploy out the box solutions like http://iiif.github.io/mirador/
* smooth thumbnail display, zooming in etc. in charter view, search results, charter overview by collection/fonds, image tools
* citation of image fragments

**Comment by StephanMa** [comment]
I am currently not sure if IIIF can be a solution for MOM-CA

See: 

> The image paths given to the IIPImage server via the FIF variable must be absolute system paths on the server machine (eg. FIF=/images/test.tif) and not paths relative to the web server document root location. Don’t forget to make sure the IIPImage server process owner has read access on the images!

And 

> In order to maximize the speed and efficiency of the system, the source images must be in a multi-resolution format.

what means: reconvert all images to tiff or jpeg 2000 (favorit)

**Comment by GVogeler** [comment]
yeah, but
* it would be solution only for images hosted by ICARus (so controll on image paths is expected)
* loris allows jpeg (http://showcase.iiif.io/showcase/loris-server.html)

**Comment by StephanMa** [comment]
> it would be solution only for images hosted by ICARus (so controll on image paths is expected) 

but only if images and server are on the same server which should not be the case. But maybe @yngwi has some ideas

**Comment by GVogeler** [comment]
As far as I've understood @yngwi the plan is to create a dedicated image server for all ICARus images, which would include image files **and** image server software. But decision on the hosting infrastructure is still under discussion.

**Comment by GVogeler** [comment]
@yngwi suggests to use https://medusa-project.github.io/cantaloupe/
