### ISSUE TITLE
Versioning Trigger increases Backupsize 

### ISSUE THREAD

**Issue by StephanMa** [icaruseu/mom-ca#596]
Since february, the size of the backup has doubled due of user versions. 
Talking to @yngwi, we should consider to disable the versioning trigger and enable for debugging purposes.

**Comment by GVogeler** [comment]
As I said already in the telco: I would suggest to switch off versioning for private collections (xrx.user hierarchy) as probably every save action in EditMOM3 is creating a new version. I would even not object to delete all existing versions in this hierarchy.

**Comment by GVogeler** [comment]
In case of IlluminiertenUrkunden User the need of Publisher the while private collection to publish changes made in only a small number of charters rises amount of data in versioning significantly (by factor 1200/number of modified charters). Allowing publication of single charters would remedy this.

**Comment by StephanMa** [comment]
Trigger was deactivated until further decisions are made
