### ISSUE TITLE
Provide access via controlled vocabularies ("index app")

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#597]
Allow access via controlled vocabularies gives the following possiblities:

* navigate through hierarchy of SKOS data in metadata.controlledVocabulary.public
* give additional information on the persons (`tei:person` in metadata.person.public) /concepts (`skos:definition` oder `skos:note`) used

**Comment by GVogeler** [comment]
follow up to #127

**Comment by StephanMa** [comment]
Index app was deployed. Can be closed?

**Comment by GVogeler** [comment]
closed with #605
