### ISSUE TITLE
hit list in index app does not show the name of the collection when hit is in collection

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#612]
e.g. http://monasterium.net/mom/index/IllUrkGlossar/Layout, where the first hit shows only `(Sammlung)` in the place where the collection name should be displayed as well.

<img width="564" alt="index-collection" src="https://user-images.githubusercontent.com/324006/26961751-7b5a7b06-4ce1-11e7-915f-efc747cbb20c.PNG">

**Comment by maburg** [comment]
The reason ist, that result.widget.xml misses to ask for my-collection
