### ISSUE TITLE
add `cei:geogname` to single charter view

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#626]
check https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/charter/xsl/cei2html.xsl : no traces to be found

**Comment by GVogeler** [comment]
should have:
1. `@title` as for `@placeName`
2. use the same css-stylse as `cei:placeName`
2. create an index list
3. in the index list use the same methods as for `cei:placeName`

**Comment by GVogeler** [comment]
Still not displayed in http://monasterium.net/mom/AT-HHStA/TullnOP/1660_VII_09/charter

**Comment by StephanMa** [comment]
Changes suggested by 
1bcf3c4
are not included in cei2html.xsd .. was there a pr revoked?

**Comment by GVogeler** [comment]
not to my knowledge. So I would suggest to integrate the change into the master branch.
