### ISSUE TITLE
tut_edit link results in 404 Not found Error

### ISSUE THREAD

**Issue by larkvi** [icaruseu/mom-ca#666]
On the User Interventions page: 
https://github.com/icaruseu/mom-ca/wiki/User-interventions:-How-to-Use-EditMOM3-Environment

This link: 
http://monasterium.net/tut_edit/

delivers a 404 Not Found error.

**Comment by GVogeler** [comment]
@JBigalke @yngwi this is the link the MOMAthon screencasts also used in http://monasterium.net/mom/momathon-tutorial . Any idea where they ended up?

**Comment by GVogeler** [comment]
@JBigalke it is probably a good idea, when you upload the screencasts into https://github.com/icaruseu/mom-ca/tree/master/wiki as well.

**Comment by StephanMa** [comment]
Because of the transfer to AWS, the localhost folder had change. It just needs to be reuoloaded to Webapp/web-inf
