### ISSUE TITLE
data model geotool

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#677]
current plans for #299 :
see: https://github.com/strec/mom-ca/tree/geo_multiple_charters and https://github.com/CTeyson/geotool
Data model:
* distinguish between data automatically extracted from geonames and stored and authenticated (by saving a charter with a `cei:placeName/@key`): geo.authorized.xml and geo.external.xml
* authorized locations cannot be deleted. They can only be modified by moderators or administrators (they have to be responsible in checking, where the authorized location is used in the charters)
* Data is stored in /db/mom-data/metadata.geo.public 
* Data model:
  * reference between cei:placeName in charter and geo-informations via `cei:placeName/@key <-> geo:location@id` if authenticated, or via `cei:placeName/string() <-> geo:location/geo:name`.
  * archives have their coordinats in the appropriat eag.xml file (in `eag:desc/eag:location`, see https://github.com/icaruseu/mom-ca/issues/678#issuecomment-343661922)
  * each `geo:location` in geo.(authorized|external).xml copies the geonames entries `name`, `name_reg`, `geoname_id`, `lat`, `lng`, `alternate_names` (or creates new elements when the location is added to the resource by hand), and adds the user who created the entry as `geo:who`. 

e.g.: 
```
<geo:toponyms xmlns:geo="http://www.monasterium.net/NS/geo">
<geo:location id="mom-geo:4" authorized="true"><geo:name>Acerra</geo:name><geo:name_reg>Acerra</geo:name_reg><geo:geoname_id>3183541</geo:geoname_id><geo:lat>40.94477</geo:lat><geo:lng>14.3714</geo:lng><geo:alternate_names>アチェッラ,Acerra,Acerra,Acerra,Acerra,Acerra,Acerra,Acerra,Acerra,Acerra,Acerra,Acerra,Acerra,Acerra,Acerrae</geo:alternate_names><geo:alternate_name>ja;アチェッラ?de;Acerra?en;Acerra?eo;Acerra?fr;Acerra?gl;Acerra?it;Acerra?la;Acerra?nap;Acerra?nl;Acerra?pl;Acerra?pt;Acerra?scn;Acerra?sl;Acerra?la;Acerrae?</geo:alternate_name><geo:who>antonella.ambrosio@unina.it</geo:who></geo:location>
...
</geo:toponyms>
```
* service output (to be processed by the map interface): see #678
Tbc

**Comment by GVogeler** [comment]
Do we need two files (for authorized and non-authorized locations) or wouldn't we better handle them in one document and distinguish be `@authorized`?

**Comment by StephanMa** [comment]
Go Mỹ mind, take an attribute

**Comment by GVogeler** [comment]
advantage attribute: all entries have the same data structure; you have to handle only one file
advantage several files: one file could become very large and difficult to handle (backups, manual changes); adding files with individual responsibilities (`atom:email`) would be possible.
But I currently I would support @StephanMa .

**Comment by GVogeler** [comment]
created `/db/mom-data/metadata.geo.public/geo.xml` with data following the definitions above.
