### ISSUE TITLE
Remove VdUEdit

### ISSUE THREAD

**Issue by StephanMa** [icaruseu/mom-ca#684]
Due of performance reason, VdU editor has to be deactivated and replaced by EditMOM3

**Comment by StephanMa** [comment]
Can be closed

**Comment by GVogeler** [comment]
http://monasterium.net/mom/saved-charters has still a link to VdUEdit. Google Analytics counts 345 calls of the URL 18.12.2017-17.12.2018:
![grafik](https://user-images.githubusercontent.com/324006/50141344-8a06b480-02a7-11e9-9e2a-1b53dbe48bcb.png)

**Comment by StephanMa** [comment]
Shall we remove this one?

I think, it depends on the user. If they are still working with this, maybe we should leave it there?

**Comment by GVogeler** [comment]
solved in branch exist-next
