### ISSUE TITLE
User reports that google is indexing private charters in EditMOM3

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#692]
https://www.google.it/search?client=firefox-b&dcr=0&q=%22de+cayecta%22&nfpr=1&sa=X&ved=0ahUKEwiJjrS8ot_XAhVR46QKHbRHBgEQvgUIJCgB&biw=1366&bih=635 has obviously indexed a private charter (http://monasterium.net/mom/smg-VSR/SMG_3_AA_III_12/edit) which should not be accessible to crawlers.

![screenshot-2017-11-27 de cayecta - google-suche](https://user-images.githubusercontent.com/324006/33280654-1457ae6c-d3a3-11e7-9099-935439a59e9a.png)

**Comment by GVogeler** [comment]
The XML of the document is available in `<div class="xrx-instance" id="icharter">` which is not displayed but can be scanned by the crawler.

**Comment by GVogeler** [comment]
Possible workaround: exclude all crawlers from `*/edit$` in robots.txt

**Comment by StephanMa** [comment]
Charter not visible any longer....
Access to private charter is denied
