### ISSUE TITLE
Erweiterung des Importmoduls für "collections"

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#7]
Listen mit Verweisen auf existierende Urkunden in MOM-CA ( witnessOrig@sameAs) importieren => moved to #263

**Comment by GVogeler** [comment]
Auflösen des `@sameAs` mit monasterium-atom:id (oder vergleichbarem) in `atom:version-of`

**Comment by StephanMa** [comment]
closed ... moved to #263
