### ISSUE TITLE
breadcrump in image view keeps fonds in link to archive

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#715]
In http://monasterium.net/mom/IT-BSNSP/02-Atti_privati/images?block=3 the breadcrump-link to the archive (`IT-BSNSP`) links to http://monasterium.net/mom/IT-BSNSP/02-Atti_privati/archive instead of http://monasterium.net/mom/IT-BSNSP/archive .

**Comment by StephanMa** [comment]
Tested with different browser... 
Seems fixed. 
Closing until further notice

**Comment by GVogeler** [comment]
The page given in the issue description still uses `https://www.monasterium.net/mom/IT-BSNSP/02-Atti_privati/archive` as `@href` in the 'IT-BSNSO' part of the breadcrumb of the navigation (`Archivbestände > IT-BSNSP >02-Atti_privati`)

**Comment by StephanMa** [comment]
![Unbenannt](https://user-images.githubusercontent.com/6735556/98366713-bc089780-2034-11eb-8d45-785745f71f33.PNG)
Couldnt verify this

**Comment by GVogeler** [comment]
Did you check it with page 2 or 3?

![grafik](https://user-images.githubusercontent.com/324006/98367169-78625d80-2035-11eb-8cfd-975f2beab885.png)

**Comment by GVogeler** [comment]
Additional problem: The linkt to the fond uses URL ending with `fonds` instead of `fond`.

**Comment by StephanMa** [comment]
very strange...
![Unbenannt2](https://user-images.githubusercontent.com/6735556/98368418-99c44900-2037-11eb-8f6e-7a8ceb12aadb.PNG)
![Unbenannt1](https://user-images.githubusercontent.com/6735556/98368421-9a5cdf80-2037-11eb-8bcd-0a76ca40a871.PNG)

**Comment by GVogeler** [comment]
Hm, you forced some intermediate proxy to update so FF now gets the correct URL, Chrome and Edge haven't realised this and keep the wrong one. So  let's close it tenatively.
