### ISSUE TITLE
user group oriented variants of the editor

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#78]
e.g.: fast data entry by archivists - scholarly editnig - database administration = Cut-and-Paste-Editor; project specific editors (define template which could be uploaded by admin-user; interface to create your own editor)

**Comment by GVogeler** [comment]
cfr #228

**Comment by StephanMa** [comment]
Should be prepared with #340. 

To Do: Define Groups inside the Editor-Template for the given User-Groups

**Comment by StephanMa** [comment]
Can be closed?

**Comment by GVogeler** [comment]
follow-up in #875
