### ISSUE TITLE
EditMOM 3 can call the `save` service even when user session is expired

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#797]
i.e. in the 30sec. befor EditMOM-3 tests the session as introduced by https://github.com/icaruseu/mom-ca/pull/571 EditMOM-3 saves a charter with `atom:author/atom:email='guest'`. This occured several times with very active users in the last year.

**Comment by GVogeler** [comment]
Can the save service check if the data submitted has a valid user (e.g. `$data/contains(atom:author/atom:email!='@'`)?

in https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/collection/service/my-collection-save.service.xml#L94 or in in https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/core/app/data/atom.xqm#L147 ?

**Comment by GVogeler** [comment]
@JBigalke suggests: add to the save-service before saving a xmldb:get-current-user()-test if the user is still logged in . If no user is logged in charter is not saved. The service returns instead a "not-logged-in" message, and EditMOM asks for authentication.

**Comment by GVogeler** [comment]
related to #556 ?

**Comment by StephanMa** [comment]
Should be fixed by https://github.com/icaruseu/mom-ca/compare/StephanMa-Issue797

**Comment by StephanMa** [comment]
Closed via #977
