### ISSUE TITLE
since #801 search link in fond view points to the search in the full archive

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#808]
In search1 users could restrict their search to fonds, and had the link in the fond view to this restriction available. Since #801 fond view link to a URL restricting only by archive: E.g. http://monasterium.net/mom/AT-DAGS/Pfarrurkunden/fond puts as "Search in AT-DAGS" http://monasterium.net/mom/search2?q=&arch=AT-DAGS instead of http://monasterium.net/mom/search2?q=&arch=AT-DAGS;Pfarrurkunden

**Comment by GVogeler** [comment]
adding `;$charter:rfondid` to https://github.com/icaruseu/mom-ca/blob/7dd04dae376763aa32d15eaca107c1496b79212e/my/XRX/src/mom/app/fond/widget/fond.widget.xml#L324 could be a solution?

**Comment by GVogeler** [comment]
search one realised it with two parameters: `arch` and `col`, e.g. http://monasterium.net/mom/search?q=&sort=date&arch=SK-AMB&col=437

**Comment by GVogeler** [comment]
solved with #812

**Comment by GVogeler** [comment]
http://monasterium.net/mom/DE-ABP;Urkunden/Urkunden/images?block=1 returns 404: `Document /db/XRX.live/mom/DE-ABP not found`, so maybe the resolver is broken?

**Comment by StephanMa** [comment]
no because the system is not able to resolve DE-ABP;Urkunden as an archive

**Comment by GVogeler** [comment]
https://github.com/icaruseu/mom-ca/blob/bf27052eff885544de55f2c76ba7259a334b16ca/my/XRX/src/mom/app/charters/widget/goto-search.widget.xml uses `$wgoto-search:id` for image preview as well as for search:
https://github.com/icaruseu/mom-ca/blob/bf27052eff885544de55f2c76ba7259a334b16ca/my/XRX/src/mom/app/charters/widget/goto-search.widget.xml#L58
https://github.com/icaruseu/mom-ca/blob/bf27052eff885544de55f2c76ba7259a334b16ca/my/XRX/src/mom/app/charters/widget/goto-search.widget.xml#L68
https://github.com/icaruseu/mom-ca/blob/bf27052eff885544de55f2c76ba7259a334b16ca/my/XRX/src/mom/app/charters/widget/goto-search.widget.xml#L74
https://github.com/icaruseu/mom-ca/blob/bf27052eff885544de55f2c76ba7259a334b16ca/my/XRX/src/mom/app/charters/widget/goto-search.widget.xml#L74
https://github.com/icaruseu/mom-ca/blob/bf27052eff885544de55f2c76ba7259a334b16ca/my/XRX/src/mom/app/charters/widget/goto-search.widget.xml#L96
https://github.com/icaruseu/mom-ca/blob/bf27052eff885544de55f2c76ba7259a334b16ca/my/XRX/src/mom/app/charters/widget/goto-search.widget.xml#L104
https://github.com/icaruseu/mom-ca/blob/bf27052eff885544de55f2c76ba7259a334b16ca/my/XRX/src/mom/app/charters/widget/goto-search.widget.xml#L113
https://github.com/icaruseu/mom-ca/blob/bf27052eff885544de55f2c76ba7259a334b16ca/my/XRX/src/mom/app/charters/widget/goto-search.widget.xml#L122
https://github.com/icaruseu/mom-ca/blob/bf27052eff885544de55f2c76ba7259a334b16ca/my/XRX/src/mom/app/charters/widget/goto-search.widget.xml#L133
https://github.com/icaruseu/mom-ca/blob/bf27052eff885544de55f2c76ba7259a334b16ca/my/XRX/src/mom/app/charters/widget/goto-search.widget.xml#L140
Thus, it is sensible to move the addition to the search paramater into https://github.com/icaruseu/mom-ca/blob/bf27052eff885544de55f2c76ba7259a334b16ca/my/XRX/src/mom/app/charters/widget/goto-search.widget.xml

**Comment by StephanMa** [comment]
What was the orginial purpose to concat the archive with the fond? The values are available in other ways

**Comment by GVogeler** [comment]
Link to search allowed to constrain the search by the current fond via setting 
`<input name="arch" type="hidden" value="DE-ABP;Urkunden" />` in search2. Thus we need a path from the fond-view to search2 with the fond as parameter.

**Comment by GVogeler** [comment]
to be solved with #816

**Comment by GVogeler** [comment]
follow-up (?) in issue #847

**Comment by GVogeler** [comment]
Problem exists still (again?) with https://www.monasterium.net/mom/DE-UAHD/HeidelbergUniversitaet/fond : Search slot `Search inDE-UAHD > HeidelbergUniversitaet >>` has only the archive in the hidden input: `<input name="context" type="hidden" value="DE-UAHD">`. @maburg, any idea on this?

**Comment by maburg** [comment]
> 
> 
> In search1 users could restrict their search to fonds, and had the link in the fond view to this restriction available. Since #801 fond view link to a URL restricting only by archive: E.g. http://monasterium.net/mom/AT-DAGS/Pfarrurkunden/fond puts as "Search in AT-DAGS" http://monasterium.net/mom/search2?q=&arch=AT-DAGS instead of http://monasterium.net/mom/search2?q=&arch=AT-DAGS;Pfarrurkunden

The problem is that an old code version is deployed!

**Comment by GVogeler** [comment]
can you identify, which commit is missing?

**Comment by maburg** [comment]
PR from October 2018: bugfix search #834.

**Comment by StephanMa** [comment]
@GVogeler can you pls try again ?

**Comment by GVogeler** [comment]
OK, now the sesrch is updated.
