### ISSUE TITLE
IllUrk-Curie crashes

### ISSUE THREAD

**Issue by StephanMa** [icaruseu/mom-ca#836]
If you try to access the collection "IlluminierteUrkundenKurie" an error appears.

eg: http://www.monasterium.net/mom/IlluminierteUrkundenKurie/1145_Dijon/charter

`The actual cardinality for parameter 1 does not match the cardinality declared in the function's signature: root($arg as node()?) node()?. Expected cardinality: zero or one, got 2.`

Possible cause: different charters with same atom:id

**Comment by GVogeler** [comment]
The atom:id of the charter named is erronously repeated in /db/mom-data/metadata.charter.public/IlluminierteUrkundenKurie/1382-07-23_Goettweig.charter.xml. Additionally the values in atom:link, the `atom:content/@src` and the `cei:text/@id` point to the wrong source. atom:id should be changed to `tag:www.monasterium.net,2011:/charter/IlluminierteUrkundenKurie/1382-07-23_Goettweig` and all references changed to `tag:www.monasterium.net,2011:/charter/IlluminierteUrkunden/1382-07-23_Goettweig`

**Comment by GVogeler** [comment]
Attentation to change values in public and in private version!

**Comment by GVogeler** [comment]
done
