### ISSUE TITLE
search in fond/collection does not restrict search

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#847]
When entering the search term "Schutz" into the serch box of http://monasterium.net/mom/AT-DAGS/Pfarrurkunden/fond ("Search inAT-DAGS > Pfarrurkunden >>") the search result (http://monasterium.net/mom/search?q=Schutz&context=AT-DAGS%3BPfarrurkunden ) includes other collections and fonds although drill down list is ticked on only on "Graz-Seckau, Diözesanarchiv > Pfarrurkunden"

**Comment by GVogeler** [comment]
Currently the search restricted to fonds via the search box in the sample above does not return any results, although http://monasterium.net/mom/AT-DAGS/Pfarrurkunden/II-101_/charter contains the search term "schenkt".

**Comment by StephanMa** [comment]
Archive:

![archive](https://user-images.githubusercontent.com/6735556/50217746-e6420500-0389-11e9-94a0-c08eca5c38fc.jpg)

Fond:

![fond](https://user-images.githubusercontent.com/6735556/50217756-eb06b900-0389-11e9-944b-722d84bcb884.JPG)

**Comment by GVogeler** [comment]
resolved with #876
