### ISSUE TITLE
Error while indexing

### ISSUE THREAD

**Issue by StephanMa** [icaruseu/mom-ca#849]
When doing a reindex, an error occurs which pointes to float values in an int field.
During a restore i was able to verify, that the errors are inside `IT-BST/BST/`.

e.g. `<cei:num rend="mezzo tarì" value="0,5">mezzo</cei:num>`

**Comment by StephanMa** [comment]
Problem: @value is defined as integer in the collection.xconf

https://github.com/icaruseu/mom-ca/blob/master/my/XRX/system/config/db/mom-data/metadata.charter.public/collection.xconf#L98

To do: change value in charters or change collection definitions

**Comment by GVogeler** [comment]
`xsd:double` would assume `value="0.5"` instead of `value="0,5"` (point not comma!)

**Comment by StephanMa** [comment]
Well then we have more then 1 problem ;)

1) charter values
2) inde definition

**Comment by GVogeler** [comment]
Can we define two index definitions, i.e. one for `cei:num/@value` and another for `cei:*/@value` ?
Or change use a double-index for `@value`in xconf (as this would include integers as well)?

**Comment by StephanMa** [comment]
I would suggest, changing index configurations to double... it should include integer as well... i will give it a try on the dev-server

**Comment by GVogeler** [comment]
changing index configuration sounds good to me.

**Comment by StephanMa** [comment]
Fixed indexfile. 
I tried to update data. Should be watched.

Closed until further notice
