### ISSUE TITLE
map in fonds view creates JavaScript error

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#862]
map view of archives in http://monasterium.net/mom/fonds does not display archives with 
JavaScript error: 
`parsererror SyntaxError: "JSON.parse: bad control character in string literal at line 1 column 6501 of the JSON data"`

**Comment by StephanMa** [comment]
Fixed..
In der `/db/mom-data/metadata.archive.public/DE-SaechsStA-D/DE-SaechsStA-D.eag.xml` war irgendwie ein CRLF in `<eag:autform>`.
Hab es entfernt und erhalte keine Fehlermeldung mehr in der Konsole

**Comment by GVogeler** [comment]
Cool, thanx!
