### ISSUE TITLE
versionOf in Bischopfsammelablass collection includes extra // in URL

### ISSUE THREAD

**Issue by larkvi** [icaruseu/mom-ca#870]
When going to a charter in the Bischopsammelablass collection, say [http://monasterium.net/mom/IlluminierteUrkundenBischofsammelablaesse/1337-08-03_Goettweig/charter](http://monasterium.net/mom/IlluminierteUrkundenBischofsammelablaesse/1337-08-03_Goettweig/charter) and following the 'This charter is an interpretation of:' link, in this case [http://monasterium.net/mom//IlluminierteUrkunden/1337-08-03_Goettweig/charter](http://monasterium.net/mom//IlluminierteUrkunden/1337-08-03_Goettweig/charter), the url adds an extra `/` in the url after `mom/`, resulting in a 404 not found error.

**Comment by StephanMa** [comment]
fixed with #871
