### ISSUE TITLE
saved-charters uses a link to EditMOM 3 which has a hard coded message

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#874]
Seems to be defined at https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/publication/publication.xqm#L543 and https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/publication/publication.xqm#L302

**Comment by GVogeler** [comment]
Can we move this into the i18n system?

**Comment by StephanMa** [comment]
yes, should be no problem here

**Comment by StephanMa** [comment]
Done.... i will do some testing and commit if afterwards

**Comment by StephanMa** [comment]
fixed with #871
