### ISSUE TITLE
charters-on-map could have a link to the fond/collection in the head

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#884]
Currently the main display of charters on a map (e.g. http://monasterium.net/mom/IT-BSNSP/08-S_Maria_della_Grotta/fond/charters-on-map?) does not contain any link to the fond or collection which is diplayed:
![grafik](https://user-images.githubusercontent.com/324006/53940022-e1513f80-40b4-11e9-8366-d2fe008d5f26.png)
This makes it difficult to navigate back to the source of the data. I would suggest to a this link to fond label in the head.

**Comment by GVogeler** [comment]
This can probably be achieved with changes in the https://github.com/icaruseu/mom-ca/blob/305738b87562c69f0760fb52b5e64382324168d7/my/XRX/src/mom/app/collection/widget/charters-on-map.widget.xml#L129 section

**Comment by StephanMa** [comment]
Fixed by #907
