### ISSUE TITLE
Collection Preface of "Illuminierte Urkunden" can't be changed

### ISSUE THREAD

**Issue by StephanMa** [icaruseu/mom-ca#898]
IllUrk was created as an user collection. On creation, such collections are added with a GUID as collectionid. Unfortunately, IllUrk was changed to have a string id instead of a GUID.

Task 1) Handle special case with string as id 

Problem: IllUrk exists in `metadata.mycollection.public` and in `xrx.user/userfolder/metadata.mycollection` . Which one should by edited? Just edit this one in the userfolder and republish it? Change the published one without change the user one?

**Comment by GVogeler** [comment]
Changes should only be made in the user space. Publication happens when user publishes full collection.

**Comment by GVogeler** [comment]
unfortunately #908 does not solve the problem for https://www.monasterium.net/mom/IlluminierteUrkunden/edit-my-collection-info.
JS-Console records
```
XFProcessor.applyChanges: xforms-submit  [ 
Object { defaultinfo: null, targetName: "submission", targetId: "ssave" }
 ] XFProcessor.js:483:37
XFProcessor.applyChanges: xforms-submit-error  [ 
Object { targetName: "submission", targetId: "ssave", "response-body": "", "resource-uri": "https://www.monasterium.net/mom/service/my-collection-save", "response-reason-phrase": "400: Bad Request: :resource-error", "location-path": "/", "error-type": "resource-error", "response-status-code": 400 }
 ] XFProcessor.js:483:37
XFProcessor.applyChanges: betterform-render-message  [ 
Object { targetName: "message", targetId: "C8", level: "ephemeral", message: "Error." }
 ]
```

**Comment by GVogeler** [comment]
solved by reindixing
