### ISSUE TITLE
Controlled vocabulary selector in EditMOM3 does not display anything in FF 67.0

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#899]
When user In EditMOM3 mark up a "keyword" `<cei:index>` (e.g. in `<cei:abstract>`, change the attribute settings to "Use Controlled Vocabulary = yes" and add `@indexName`, the  attribute `indexName` should display a selection list from `metadata.ControlledVocabulary.public//skos:ConceptScheme/skos:prefLabel`. Currently the selection list is empty.
JavaScript console does not show any error.
Probably involved files are : https://github.com/icaruseu/mom-ca/blob/7dd04dae376763aa32d15eaca107c1496b79212e/my/XRX/src/mom/app/collection/service/editMomgetControlledVoc.service.xml, https://github.com/icaruseu/mom-ca/blob/7dd04dae376763aa32d15eaca107c1496b79212e/my/XRX/src/core/app/xrx/js/jquery.ui.xrxAttributes.js#L246 and maybe https://github.com/icaruseu/mom-ca/blob/7dd04dae376763aa32d15eaca107c1496b79212e/my/XRX/src/mom/app/collection/js/jquery.ui.xrxAttributes.js

**Comment by StephanMa** [comment]
Seems to work ?

![Unbenannt](https://user-images.githubusercontent.com/6735556/59905614-f5704100-9406-11e9-9bad-735153734391.PNG)

https://www.monasterium.net/mom/AT-StiAA/Urkunden/1223_III_04/edit?mode=full

Marked some text, add a "Sachindex", changed ControlledVoc to "Yes", added indexName and all indices are listed

**Comment by GVogeler** [comment]
Seems to be a Firefox problem (FF 67.0.3): Logged in as georg.vogeler@gmx.de, creating a new charter in a new collection (https://www.monasterium.net/mom/310b4273-52ce-486a-8b42-7352ce886a9c/11fc7023-0362-4b48-bc70-2303620b4802/edit) it does not work, unfortunately 
![grafik](https://user-images.githubusercontent.com/324006/59906290-a9be9700-9408-11e9-81e2-801ccbc2aa01.png)
The same with an existing private charter in a user created collection and as illuminierteUrkunden@gmail.com (tested on https://www.monasterium.net/mom/594c71db-950b-4b33-8712-2fad58731d1b/eaa59870-0360-4a2c-afca-919921fb0b2e/edit)
In Chrome, the list is visible.
CSS related?

**Comment by StephanMa** [comment]
Ok it seems that is something weired...
jQuery has all the indices and you can choose them by using the arrow-keys on the keyboard. Somehow, the drop-down menu isnt rendered correctly in the newer ff version. 
I will have a look

**Comment by GVogeler** [comment]
resolved with #901
