### ISSUE TITLE
XRX-error when logging out while on https://www.monasterium.net/mom/IlluminierteUrkunden/edit-my-collection-info?

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#910]
Usually when logging out on private pages MOM-CA responds with a "warning, cannot be accessed". When logging out while on edit-my-collection-info MOM-CA returns an XRX-error `In function: metadata:entry(xs:string, xs:string) [1:1321:/db/XRX.live/mom/app/metadata/metadata.xqm]`.

**Comment by StephanMa** [comment]
It seems that xquery isnt able to find anything inside of `collection("/db/mom-data/xrx.user")`

Tested:
```xquery
let $entry := doc("/db/mom-data/xrx.user/illuminierteurkunden%40gmail.com/metadata.mycollection/IlluminierteUrkunden/IlluminierteUrkunden.mycollection.xml")
let $entry_1 := collection("/db/mom-data/xrx.user")//atom:id[./text() = $entry//atom:id/text()]/ancestor::atom:entry
```

$entry delivers the desired result.
$entry_1 is empty

I already changed the indexfile of xrx.user to include `atom:id` as well... sadly without results

**Comment by StephanMa** [comment]
Changed access to user-related collection.

**Comment by StephanMa** [comment]
Source is deployed
