### ISSUE TITLE
images.monsterium.net does not accept https:// calls

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#913]
https://www.monasterium.net/mom/CSGIII/Nr_1235_S_204-206/charter is calling https://images.monasterium.net/pics/903/K.._MOM-Bilddateien._%7EStiASG2jpgweb._%7EStiASG_12340505_A4-B3_r.jpg which should be `http://` instead of `https://` The behaviour is probably triggered by https://github.com/icaruseu/mom-ca/blob/cc9865f5caedad0e00b5a2933176ee5ffa12c351/my/XRX/src/mom/app/charter/widget/charter.widget.xml#L297 . 
Other places, which might have to be changed : 

- https://github.com/icaruseu/mom-ca/search?q=cei%3Aimage_server_address&unscoped_q=cei%3Aimage_server_address 
- https://github.com/icaruseu/mom-ca/search?q=image-server-base-url&unscoped_q=image-server-base-url

**Comment by GVogeler** [comment]
Suggestion: Modify image server creation in a way that:
1. checks if `$image_server_adress` starts with http => then do nothing
2. if `$image_server_adress` = `images.monasterium.net` then use default (http://)
3. everything else just stick to calling protocoll.
This would give us the possibility to controll the image server adress completely in edit-collection.

To be inserted into https://github.com/icaruseu/mom-ca/blob/cc9865f5caedad0e00b5a2933176ee5ffa12c351/my/XRX/src/mom/app/charter/widget/charter.widget.xml#L289

**Comment by larkvi** [comment]
Does this still need to be done? The [test charter ](https://www.monasterium.net/mom/CSGIII/Nr_1235_S_204-206/charter) that I reported the initial problem with does nto seem to be experiencing the issue now. Has it been resolved through another means?

**Comment by StephanMa** [comment]
Charter is showen with images. Seems to be fixed?

**Comment by StephanMa** [comment]
closed until further notice
