### ISSUE TITLE
display of charters in meta-collections seems to have problems

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#915]
https://www.monasterium.net/mom/Fulda/collection ist a meta-collection (https://github.com/icaruseu/mom-ca/wiki/MOM-CA:-collections). It lists abstracts from several archival fonds. The single charter in the list e.g. https://www.monasterium.net/mom/Fulda/collection?block=2 links to something like https://www.monasterium.net/mom/Fulda/charter?atomid=tag:www.monasterium.net,2011:/charter/DE-BPSFulda/urkunden/7 which returns an simple "Error".
Same situation with https://www.monasterium.net/mom/collections: List of charters (e.g. https://www.monasterium.net/mom/DO/collection?block=9) links to https://www.monasterium.net/mom/DO/charter?atomid=tag:www.monasterium.net,2011:/charter/AT-DOZA/Urkunden/168 which returns "Error".

**Comment by GVogeler** [comment]
maybe related to https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/charter/charter.xqm#L209-L215 ?

**Comment by StephanMa** [comment]
Should be fixed with 09842da
directly activated in live
