### ISSUE TITLE
`ant compile-xrx-app` stores the full source code not only updated

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#923]
When executing the ant target for compilation of a single app (`ant compile-xrx-app -Dapp=...`), MOM-CA is expected to check for updated source code files, store them into eXist-db, and compile the app named in the `-Dapp` parameter. In the MOM-CA docker instance it creates instead a full copy of the source code files from the `my/mom`-directory before compilation, which takes significant more time, of course.

**Comment by StephanMa** [comment]
Just initialize the tmp file, when doing clear-xrx.
