### ISSUE TITLE
Labels in drop down list for index/register functionalities have typos

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#926]
The collection-register (https://github.com/icaruseu/mom-ca/blob/305738b87562c69f0760fb52b5e64382324168d7/my/XRX/src/mom/app/collection/widget/collection-register.widget.xml) should replace:
`Witnisses`-> `Witnesses`
`Issueres` ->`Issuers`

**Comment by GVogeler** [comment]
to be solved by #931

**Comment by StephanMa** [comment]
Closed by https://github.com/icaruseu/mom-ca/pull/931
