### ISSUE TITLE
Can 'register'-app be applied to archival fonds or only to collections?

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#930]
https://www.monasterium.net/mom/AT-StiAA/Urkunden/collection-register?modus=collection suggests that it might be possible to use the register-app in archival fonds as well: extraction of index entries works. But, when clicking on an entry no charters are returned.
Similar https://www.monasterium.net/mom/AT-StiAGe/Urkunden/collection-register does not select any entries, although https://www.monasterium.net/mom/AT-StiAGe/Urkunden/1188/charter has relevant markup.

**Comment by GVogeler** [comment]
It seems that we have to use a mechanism to create the archival fond-id in https://github.com/icaruseu/mom-ca/blob/305738b87562c69f0760fb52b5e64382324168d7/my/XRX/src/mom/app/collection/widget/collection-register.widget.xml#L45 e.g. https://github.com/icaruseu/mom-ca/blob/305738b87562c69f0760fb52b5e64382324168d7/my/XRX/src/mom/app/charter/charter.xqm#L41-L45

**Comment by GVogeler** [comment]
```
import module namespace charter="http://www.monasterium.net/NS/charter" at ../charter/charter.xqm;
```
is already sufficient to have the variables available?

**Comment by StephanMa** [comment]
It seems that its callable from fonds but does not return any result, see

https://www.monasterium.net/mom/AT-DOZA/Urkunden/collection-register?modus=collection

I think, the buildung of the atomid has to be reworked because the collection just has one identifier but the fonds have two. 

Suggestions?, @JBigalke

**Comment by JBigalke** [comment]
It should be possible, 
i worked with a parameter called modus, for collections and my-collections. 
It should be possible to a new modus and add a third way to create the id. 

I can try to do it.

**Comment by JBigalke** [comment]
Should be solved with pull request:
Fondregistersearch #933 
I tested it with the fond IT-BSNSP/03-Compre_e_vendite.
Biggest Problem is Whitespace inside of person-tags.  
For example: 
<cei:persName certainty="alta" reg="Adelferio" type="maschile"> <cei:foreign> Adelferius</cei:foreign> is only be found with ALL and not with A as first Character.

**Comment by GVogeler** [comment]
As the problem to extract archive/fond and collection from an URI is a common task in MOM-CA I wonder if we cannot reuse a solution already implemented elsewhere (see https://github.com/icaruseu/mom-ca/issues/930#issuecomment-585211364)

**Comment by StephanMa** [comment]
There are so many places where this kind of extractions are defined...  I give up pointing to this methods. But you are totally right. It should be used

**Comment by GVogeler** [comment]
So, I would suggest, to reuse anyone for now (@StephanMa your first choice?) and create a refactoring issue where we collect all other occurences for solutions of this task.
We could add to this list: https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/archive/archive.xqm#L34-L39, https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/collection/collections.xqm#L57, https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/fond/fond.xqm#L63-L81, https://github.com/icaruseu/mom-ca/blob/7dd04dae376763aa32d15eaca107c1496b79212e/my/XRX/src/core/app/data/data.xqm#L53-L72. 
And I still have the impression that https://github.com/icaruseu/mom-ca/blob/305738b87562c69f0760fb52b5e64382324168d7/my/XRX/src/mom/app/charter/charter.xqm#L41-L45 gives us an insight how this generic function could look like:

collection/fond-distinction:

1. tokenize(uri, '/')
2. use part between `monasterium.net/mom` and `last()` as representation of the object `$identifier`
3. if count(2)=>archive/fond, count(1)=> collection
3. return {objecttype, exist-db-location, partial ids with objecttypes (e.g. <archiveid>...</archiveid><fondid>...</fondid>)}

**Comment by JBigalke** [comment]
A Option to distinct between collection and mycollection is needed. 
This was the main reason to create the modus parameter inside the register app.

**Comment by GVogeler** [comment]
Distinguish between my-collection and public collection makes completely sense, and your solution in the PR #933 seems to be working to me. If @StephanMa agrees I would not mind to deploy it, but we should at least create an refactoring issue collecting the places in which we've found this type of analyis.

**Comment by StephanMa** [comment]
Will merge it now and deploy it tomorrow.

@JBigalke can you please create a follow-up issue?

**Comment by StephanMa** [comment]
Deployed and tested 
https://www.monasterium.net/mom/AT-DOZA/Urkunden/collection-register?modus=fond

**Comment by GVogeler** [comment]
Hmm, I made a test with https://www.monasterium.net/mom/AT-KLA/AUR/collection-register?modus=fond which includes https://www.monasterium.net/mom/AT-KLA/AUR/AT-KLA_418-B-C_864_St/charter. The XPath `cei:body//cei:placeName` returns one result in the XML ('Wien'), but the places-selection returns only "No result found". Anything I'm doing wrong?

**Comment by StephanMa** [comment]
Searching for PLacename "Wien" in https://www.monasterium.net/mom/AT-KLA/AUR/collection-register?modus=fond does return the charter 864 

![Unbenannt](https://user-images.githubusercontent.com/6735556/74652866-451a2e80-5187-11ea-9411-9b128bef7888.PNG)

**Comment by GVogeler** [comment]
OK, I had to do a better website-reload. No it works with me as well!
