### ISSUE TITLE
archivist does not see released charters in "charters-to-publish"

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#940]
reports Lena Weileder:
![grafik](https://user-images.githubusercontent.com/324006/75562768-6ad9ea00-5a49-11ea-8021-761090888eb8.png) although she received a notification e-mail.

**Comment by GVogeler** [comment]
Documentations to the functionality: https://github.com/icaruseu/mom-ca/wiki/MOM-CA:-User-roles ist rather brief on the technical side (doesn't tell anything about the release/publication workflow and the involved apps)

**Comment by StephanMa** [comment]
Maybe the charter was deleted afterwards?

**Comment by GVogeler** [comment]
I tested it with a newly (and only temporarly assigned) archivist:
1. archivist does not receive notification (see #958)
2. moderator receives notification
3. archivist and moderator see released charter in ...to Publish; deleting the charter as moderator deletes it from the archivists list of charters to publish as well.
So, problem is currently not reproducable.
