### ISSUE TITLE
search constraint by collection can result in exclusion of a search result from the hit list

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#946]
Searching for `"S. de Aquila; Gratis de mandato domini nostri pape"` in the general search (https://www.monasterium.net/mom/search?q=%22S.+de+Aquila%3B+Gratis+de+mandato+domini+nostri+pape%22&option=and&img=&annotations=&sort=date&categories=&context=) results in a correct hit in https://www.monasterium.net/mom/IlluminierteUrkunden/1396-08-30_Muenchen/charter.

Restricting the search to the "Illuminierte Urkunden" collection (https://www.monasterium.net/mom/search?q=%22S.+de+Aquila%3B+Gratis+de+mandato+domini+nostri+pape%22&sort=date&context=IlluminierteUrkunden) returns no visibile hit but a count of the hit in the drill down menu on the left ("lluminierteUrkunden (0) (1)").

**Comment by GVogeler** [comment]
https://github.com/icaruseu/mom-ca/pull/767/files might give a hint, by which files this could be caused.

**Comment by maburg** [comment]
Ich vermute eher ein Zeichenproblem, also der ";", bei einem anderen Versuch gibts wiederum keine Probleme, z.B.: http://www.monasterium.net/mom/search?q=Stefano+dell%27Aquila+sind+sehr+zur%C3%BCckhaltend+dekoriert&option=and&img=&annotations=&sort=date&categories=&context=IlluminierteUrkunden . 
Der Parameter q wird in "https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/search/js/jquery.ui.search.js" bearbeitet, vielleicht muss man hier ansetzen.

**Comment by GVogeler** [comment]
It keeps to be strange: 
https://www.monasterium.net/mom/search?q=Scriptor&option=and&img=&annotations=&sort=date&categories= counts 174 hits in the Illuminierte Urkunde collection, but restricting it to the collection (https://www.monasterium.net/mom/search?q=Scriptor&option=and&img=&annotations=&sort=date&categories=&context=IlluminierteUrkunden) returns only one hit.

**Comment by GVogeler** [comment]
Another example (https://www.monasterium.net/mom/search?q=Zu+weiteren+Werken+des+Skriptors+Hieronymus+de+Ferentino&option=and&img=&annotations=&sort=date&categories=&context= returing two hits in the collection, but only one when restricting to the collection) suggest to include the occurrence of the hit in XML-Tree (`cei:diplomaticAnalysis/cei:p`) into account.

**Comment by StephanMa** [comment]
@GVogeler  For your last example: the counter isnt correct. It should only return one (1396-06-17_Prag).  The problem seems to be in the restriction of the search term...

Searching for "Zu weiteren Werken des Skriptors Hieronymus de Ferentino" does return two charters (somehow). Lucene shows hits for "des" . But searching for  `'  "Zu weiteren Werken des Skriptors Hieronymus de Ferentino"' `works as expected

**Comment by StephanMa** [comment]
For test purposes:

```xquery
xquery version "3.1";
declare namespace exist="http://exist.sourceforge.net/NS/exist";
declare namespace tei="http://www.tei-c.org/ns/1.0";
let $docs := ft:query(collection("/db/mom-data/metadata.charter.public/IlluminierteUrkunden")//*, '"Zu weiteren Werken des Skriptors Hieronymus de Ferentino"')
return for $doc in $docs
    return (base-uri($doc), $doc)
```

**Comment by GVogeler** [comment]
Unfortunately, changing to phrase search is a) not covering the observation in my post (https://github.com/icaruseu/mom-ca/issues/946#issuecomment-633504295) and b) does not affect the initial observation: https://www.monasterium.net/mom/search?q=%22S.+de+Aquila%3B+Gratis+de+mandato+domini+nostri+pape%22&option=and&img=&annotations=&sort=date&categories= returns one hit, restricting it to the IlluminierteUrkunden collection returns no hit: https://www.monasterium.net/mom/search?q=%22S.+de+Aquila%3B+Gratis+de+mandato+domini+nostri+pape%22&option=and&img=&annotations an=&sort=date&categories=&context=IlluminierteUrkunden, although 
```
xquery version "3.1";
declare namespace exist="http://exist.sourceforge.net/NS/exist";

let $searchstring := "S. de Aquila; Gratis de mandato domini nostri pape"
let $docs := ft:query(collection("/db/mom-data/metadata.charter.public/IlluminierteUrkunden")//*, $searchstring)
return for $doc in $docs
    return (base-uri($doc), $doc)
```
returns 1 hit.

**Comment by GVogeler** [comment]
@maburg as for search.js: You are thinking of 
https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/search/js/jquery.ui.search.js#L202-L220 ? This seems to collect the selections to prepare the submission of the query to database, which would then be passed-on to https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/search/search.xqm where https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/search/search.xqm#L332-L334 is triggered and https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/search/search.xqm#L332-L334 is built, the very search is executed in https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/search/search.xqm#L503 and onwards.

**Comment by StephanMa** [comment]
@GVogeler thats not what i meant....

There are two different functions with different restrictions.

See https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/search/search.xqm#L471

I would suggest, that there are differences in building the search string

**Comment by GVogeler** [comment]
@StephanMa, yes, of course, there are. To understand your comment, let me describe the procedure as far as I can understand it by now:

1.  `search:is-first-action()` is triggered by https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/search/search.xqm#L318, 
2. `search:is-browse-action()` is triggered by https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/search/search.xqm#L326
3. `search:is-filter-action()` is triggered by https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/search/search.xqm#L332

The search call _with_ constraint (https://www.monasterium.net/mom/search?q=%22S.+de+Aquila%3B+Gratis+de+mandato+domini+nostri+pape%22&option=and&img=&annotations=&sort=date&categories=&context=IlluminierteUrkunden  )triggers `search:is-filter-action()`, while the search _without_ constraint (https://www.monasterium.net/mom/search?q="S.+de+Aquila%3B+Gratis+de+mandato+domini+nostri+pape"&option=and&img=&annotations=&sort=date&categories=) triggers `search:is-first-action()`.
In the `search:is-filter-action()` we have https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/search/search.xqm#L516 setting the constraints to the query executed in https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/search/search.xqm#L504 - and from this point I'm lost. You have a suggestion, how the very query (i.e. `$query-string`) is created in this process is built?

**Comment by StephanMa** [comment]
I could pinpoint the error to 
https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/search/search.xqm#L436

Somewhere deep inside of this function, the charter disappear. Im struggling very hard to understand whats going on there. Maybe this part should be rewritten entirely...

**Comment by GVogeler** [comment]
OK, at least a lead. The function applies the filter created by clicking on the drill-down select boxes to the result set of the initial search. The $map contains a key/value list of the hits per drill-down category. The search:categories-included() and search: categories-excluded() functions use session variables. They all are merged into an intersection.
Strategy for drill-down in general would be to use the information about the initial result set to reduce searching time and to compare drill-down results with initial result. There seems to be a dedicated faceted search in existdb 5.0: https://github.com/eXist-db/exist/pull/2629 and an old paper on the subject https://www.narcis.nl/publication/RecordID/oai%3Adare.uva.nl%3Apublications%2Fcbe4751b-936f-4f2a-94e8-92ac5ceb53c8 which we could use to reimplement the functionality.
