### ISSUE TITLE
Link to charter editor from saved charters does not react in Firefox

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#957]
In Firefox79.0  Neither the "edit in EditMOM3" link in https://www.monasterium.net/mom/MonBoicorumVI/b2136236-9343-46b1-86f2-c7fbbc239bc3/charter nor the editor link in MyArchive (https://www.monasterium.net/mom/MonBoicorumVI/b2136236-9343-46b1-86f2-c7fbbc239bc3/charter?q=%22Num.%20I%22) show a reaction:
Console does not show any error: XFProcessor.applyChanges: DOMActivate  [ 
Object { defaultinfo: null, targetName: "trigger", targetId: "C49" }
 ] XFProcessor.js:483:37
XFProcessor.applyChanges: betterform-load-uri  [ 
Object { targetName: "load", targetId: "C52", show: "new", uri: "/mom/MonBoicorumVI/b2136236-9343-46b1-86f2-c7fbbc239bc3/edit?mode=full" }
 ] XFProcessor.js:483:37
XFProcessor._handleBetterFormLoadURI xmlEvent: 
Object { bubbles: true, cancelable: false, contextInfo: {…}, currentTarget: null, eventPhase: 1, propertyNames: (4) […], target: null, timeStamp: 1596780535663, type: "betterform-load-uri" }

In Chrome a new tabs with the editor opens as expected.

Is this a behaviour reproducable with FF?

**Comment by GVogeler** [comment]
Maybe replacing the BetterForm based call for `/mom/{atom:id}/edit` by an explicit `a/@href` would be an easy work around?

**Comment by StephanMa** [comment]
Do you have a popupblocker enabled?

**Comment by GVogeler** [comment]
Yes, that's it! Although usually I get a warning if a pop-up is blocked. Maybe it's because the BetterForm call is handled as a new tab FF.
