### ISSUE TITLE
Remove Flash Image Viewer

### ISSUE THREAD

**Issue by yngwi** [icaruseu/mom-ca#976]
The Flash Player is more and more unavailable in various OS and browser settings. For instance, Microsoft currently removes the installation included in Windows. We should remove the player and either:

1. Replace the `Open image in Flash viewer` link with something like "Open image in new tab" and just directly open the image file when clicking on the link the same way we do when the user directly clicks on the image.
2. Replace it with a JS based image viewer (combined with IIIF?)

**Comment by yngwi** [comment]
I guess for now the most efficient way to tackle this is solution #1 but an IIIF based JS image viewer (not only in a new tab but directly on the charter page) would be preferable in the long run but is probably out of scope for this issue (flash player removal)

**Comment by GVogeler** [comment]
see #494 for JS-replacement.

**Comment by GVogeler** [comment]
solved with https://github.com/icaruseu/mom-ca/pull/995#event-4209837175
